#include <C:\Users\Saverio\Documents\SourceTree\Impostor\src\Impostor.Plugins.SemanticAnnotator\include\cowl.h>
#include <new>

unsigned short (*_0)(unsigned short) = &::ulib_uint16_floor2;
unsigned int (*_1)(unsigned int) = &::ulib_uint32_floor2;
unsigned long long (*_2)(unsigned long long) = &::ulib_uint64_floor2;
unsigned short (*_3)(unsigned short) = &::ulib_uint16_ceil2;
unsigned int (*_4)(unsigned int) = &::ulib_uint32_ceil2;
unsigned long long (*_5)(unsigned long long) = &::ulib_uint64_ceil2;
unsigned int (*_6)(unsigned short) = &::ulib_uint16_log2;
unsigned int (*_7)(unsigned int) = &::ulib_uint32_log2;
unsigned int (*_8)(unsigned long long) = &::ulib_uint64_log2;
unsigned int (*_9)(unsigned int) = &::ulib_uint_floor2;
unsigned int (*_10)(unsigned int) = &::ulib_uint_ceil2;
unsigned int (*_11)(unsigned int) = &::ulib_uint_log2;
double (*_12)(double) = &::ulib_float_prev;
double (*_13)(double) = &::ulib_float_next;
unsigned int (*_14)(unsigned char) = &::ulib_uint_pow2;
bool (*_15)(unsigned int) = &::ulib_uint_is_pow2;
unsigned int (*_16)(unsigned char) = &::p_ubit_count_set_8;
unsigned int (*_17)(unsigned short) = &::p_ubit_count_set_16;
unsigned int (*_18)(unsigned int) = &::p_ubit_count_set_32;
unsigned int (*_19)(unsigned long long) = &::p_ubit_count_set_64;
unsigned int (*_20)(unsigned char) = &::p_ubit_first_set_8;
unsigned int (*_21)(unsigned short) = &::p_ubit_first_set_16;
unsigned int (*_22)(unsigned int) = &::p_ubit_first_set_32;
unsigned int (*_23)(unsigned long long) = &::p_ubit_first_set_64;
bool (*_24)(char) = &::ulib_char_is_upper;
bool (*_25)(char) = &::ulib_char_is_lower;
char (*_26)(char) = &::ulib_char_to_upper;
char (*_27)(char) = &::ulib_char_to_lower;
bool (*_28)(const char*, const char*) = &::ulib_str_equals;
bool (*_29)(const char*, unsigned long long) = &::ulib_str_is_upper;
bool (*_30)(const char*, unsigned long long) = &::ulib_str_is_lower;
void (*_31)(char*, const char*, unsigned long long) = &::ulib_str_to_upper;
void (*_32)(char*, const char*, unsigned long long) = &::ulib_str_to_lower;
int (*_33)(const char*, char**, unsigned int) = &::ulib_str_to_int;
unsigned int (*_34)(const char*, char**, unsigned int) = &::ulib_str_to_uint;
double (*_35)(const char*, char**) = &::ulib_str_to_float;
struct p_ustring_sizing& (p_ustring_sizing::*_36)(struct p_ustring_sizing&&) = &p_ustring_sizing::operator=;
struct p_ustring_large& (p_ustring_large::*_37)(struct p_ustring_large&&) = &p_ustring_large::operator=;
UString& (UString::*_38)(UString&&) = &UString::operator=;
unsigned int (*_39)(struct p_ustring_large) = &::p_ustring_large_size;
unsigned int (*_40)(UString) = &::ustring_size;
unsigned int (*_41)(UString) = &::ustring_length;
UString (*_42)(const char*) = &::ustring_assign_buf;
UString (*_43)(const char*) = &::ustring_copy_buf;
UString (*_44)(const char*) = &::ustring_wrap_buf;
UString (*_45)(UString, unsigned int, unsigned int) = &::ustring_range;
bool (*_46)(UString) = &::ustring_is_upper;
bool (*_47)(UString) = &::ustring_is_lower;
bool (*_48)(UString) = &::ustring_is_null;
bool (*_49)(UString) = &::ustring_is_empty;
unsigned int (*_50)(unsigned long long) = &::p_ulib_hash_int64;
unsigned int (*_51)(const char*) = &::ulib_hash_kr2;
unsigned int (*_52)(unsigned int, const void*, unsigned long long) = &::ulib_hash_mem_kr2;
unsigned int (*_53)(const char*) = &::ulib_hash_djb2;
unsigned int (*_54)(unsigned int, const void*, unsigned long long) = &::ulib_hash_djb2_mem;
unsigned int (*_55)(unsigned int, unsigned int) = &::ulib_hash_combine;
UHash_ulib_int& (UHash_ulib_int::*_56)(UHash_ulib_int&&) = &UHash_ulib_int::operator=;
UHash_Loop_ulib_int& (UHash_Loop_ulib_int::*_57)(UHash_Loop_ulib_int&&) = &UHash_Loop_ulib_int::operator=;
UHash_ulib_uint& (UHash_ulib_uint::*_58)(UHash_ulib_uint&&) = &UHash_ulib_uint::operator=;
UHash_Loop_ulib_uint& (UHash_Loop_ulib_uint::*_59)(UHash_Loop_ulib_uint&&) = &UHash_Loop_ulib_uint::operator=;
UHash_ulib_ptr& (UHash_ulib_ptr::*_60)(UHash_ulib_ptr&&) = &UHash_ulib_ptr::operator=;
UHash_Loop_ulib_ptr& (UHash_Loop_ulib_ptr::*_61)(UHash_Loop_ulib_ptr&&) = &UHash_Loop_ulib_ptr::operator=;
UHash_UString& (UHash_UString::*_62)(UHash_UString&&) = &UHash_UString::operator=;
UHash_Loop_UString& (UHash_Loop_UString::*_63)(UHash_Loop_UString&&) = &UHash_Loop_UString::operator=;
bool (*_64)(const UHash_ulib_int*) = &::uhash_is_map_ulib_int;
UHash_ulib_int (*_65)(UHash_ulib_int*) = &::uhash_move_ulib_int;
unsigned int (*_66)(const UHash_ulib_int*, unsigned int) = &::uhash_next_ulib_int;
bool (*_67)(const UHash_ulib_int*, const UHash_ulib_int*) = &::uhset_equals_ulib_int;
unsigned int (*_68)(const UHash_ulib_int*) = &::p_uhash_occupied_ulib_int;
bool (*_69)(const UHash_ulib_uint*) = &::uhash_is_map_ulib_uint;
UHash_ulib_uint (*_70)(UHash_ulib_uint*) = &::uhash_move_ulib_uint;
unsigned int (*_71)(const UHash_ulib_uint*, unsigned int) = &::uhash_next_ulib_uint;
bool (*_72)(const UHash_ulib_uint*, const UHash_ulib_uint*) = &::uhset_equals_ulib_uint;
unsigned int (*_73)(const UHash_ulib_uint*) = &::p_uhash_occupied_ulib_uint;
bool (*_74)(const UHash_ulib_ptr*) = &::uhash_is_map_ulib_ptr;
UHash_ulib_ptr (*_75)(UHash_ulib_ptr*) = &::uhash_move_ulib_ptr;
unsigned int (*_76)(const UHash_ulib_ptr*, unsigned int) = &::uhash_next_ulib_ptr;
bool (*_77)(const UHash_ulib_ptr*, const UHash_ulib_ptr*) = &::uhset_equals_ulib_ptr;
unsigned int (*_78)(const UHash_ulib_ptr*) = &::p_uhash_occupied_ulib_ptr;
bool (*_79)(const UHash_UString*) = &::uhash_is_map_UString;
UHash_UString (*_80)(UHash_UString*) = &::uhash_move_UString;
unsigned int (*_81)(const UHash_UString*, unsigned int) = &::uhash_next_UString;
bool (*_82)(const UHash_UString*, const UHash_UString*) = &::uhset_equals_UString;
unsigned int (*_83)(const UHash_UString*) = &::p_uhash_occupied_UString;
UVersion& (UVersion::*_84)(UVersion&&) = &UVersion::operator=;
UVersion (*_85)(unsigned int, unsigned int, unsigned int) = &::uversion;
struct p_uvec_sizing_char& (p_uvec_sizing_char::*_86)(struct p_uvec_sizing_char&&) = &p_uvec_sizing_char::operator=;
struct p_uvec_large_char& (p_uvec_large_char::*_87)(struct p_uvec_large_char&&) = &p_uvec_large_char::operator=;
UVec_char& (UVec_char::*_88)(UVec_char&&) = &UVec_char::operator=;
UVec_Loop_char& (UVec_Loop_char::*_89)(UVec_Loop_char&&) = &UVec_Loop_char::operator=;
struct p_uvec_sizing_ulib_byte& (p_uvec_sizing_ulib_byte::*_90)(struct p_uvec_sizing_ulib_byte&&) = &p_uvec_sizing_ulib_byte::operator=;
struct p_uvec_large_ulib_byte& (p_uvec_large_ulib_byte::*_91)(struct p_uvec_large_ulib_byte&&) = &p_uvec_large_ulib_byte::operator=;
UVec_ulib_byte& (UVec_ulib_byte::*_92)(UVec_ulib_byte&&) = &UVec_ulib_byte::operator=;
UVec_Loop_ulib_byte& (UVec_Loop_ulib_byte::*_93)(UVec_Loop_ulib_byte&&) = &UVec_Loop_ulib_byte::operator=;
struct p_uvec_sizing_ulib_int& (p_uvec_sizing_ulib_int::*_94)(struct p_uvec_sizing_ulib_int&&) = &p_uvec_sizing_ulib_int::operator=;
struct p_uvec_large_ulib_int& (p_uvec_large_ulib_int::*_95)(struct p_uvec_large_ulib_int&&) = &p_uvec_large_ulib_int::operator=;
UVec_ulib_int& (UVec_ulib_int::*_96)(UVec_ulib_int&&) = &UVec_ulib_int::operator=;
UVec_Loop_ulib_int& (UVec_Loop_ulib_int::*_97)(UVec_Loop_ulib_int&&) = &UVec_Loop_ulib_int::operator=;
struct p_uvec_sizing_ulib_uint& (p_uvec_sizing_ulib_uint::*_98)(struct p_uvec_sizing_ulib_uint&&) = &p_uvec_sizing_ulib_uint::operator=;
struct p_uvec_large_ulib_uint& (p_uvec_large_ulib_uint::*_99)(struct p_uvec_large_ulib_uint&&) = &p_uvec_large_ulib_uint::operator=;
UVec_ulib_uint& (UVec_ulib_uint::*_100)(UVec_ulib_uint&&) = &UVec_ulib_uint::operator=;
UVec_Loop_ulib_uint& (UVec_Loop_ulib_uint::*_101)(UVec_Loop_ulib_uint&&) = &UVec_Loop_ulib_uint::operator=;
struct p_uvec_sizing_ulib_float& (p_uvec_sizing_ulib_float::*_102)(struct p_uvec_sizing_ulib_float&&) = &p_uvec_sizing_ulib_float::operator=;
struct p_uvec_large_ulib_float& (p_uvec_large_ulib_float::*_103)(struct p_uvec_large_ulib_float&&) = &p_uvec_large_ulib_float::operator=;
UVec_ulib_float& (UVec_ulib_float::*_104)(UVec_ulib_float&&) = &UVec_ulib_float::operator=;
UVec_Loop_ulib_float& (UVec_Loop_ulib_float::*_105)(UVec_Loop_ulib_float&&) = &UVec_Loop_ulib_float::operator=;
struct p_uvec_sizing_ulib_ptr& (p_uvec_sizing_ulib_ptr::*_106)(struct p_uvec_sizing_ulib_ptr&&) = &p_uvec_sizing_ulib_ptr::operator=;
struct p_uvec_large_ulib_ptr& (p_uvec_large_ulib_ptr::*_107)(struct p_uvec_large_ulib_ptr&&) = &p_uvec_large_ulib_ptr::operator=;
UVec_ulib_ptr& (UVec_ulib_ptr::*_108)(UVec_ulib_ptr&&) = &UVec_ulib_ptr::operator=;
UVec_Loop_ulib_ptr& (UVec_Loop_ulib_ptr::*_109)(UVec_Loop_ulib_ptr&&) = &UVec_Loop_ulib_ptr::operator=;
struct p_uvec_sizing_UString& (p_uvec_sizing_UString::*_110)(struct p_uvec_sizing_UString&&) = &p_uvec_sizing_UString::operator=;
struct p_uvec_large_UString& (p_uvec_large_UString::*_111)(struct p_uvec_large_UString&&) = &p_uvec_large_UString::operator=;
UVec_UString& (UVec_UString::*_112)(UVec_UString&&) = &UVec_UString::operator=;
UVec_Loop_UString& (UVec_Loop_UString::*_113)(UVec_Loop_UString&&) = &UVec_Loop_UString::operator=;
UVec_char (*_114)() = &::uvec_char;
UVec_char (*_115)(char*, unsigned int) = &::uvec_assign_char;
UVec_char (*_116)(char*, unsigned int) = &::uvec_wrap_char;
char* (*_117)(const UVec_char*) = &::uvec_data_char;
unsigned int (*_118)(const UVec_char*) = &::uvec_size_char;
unsigned int (*_119)(const UVec_char*) = &::uvec_count_char;
void (*_120)(UVec_char*, unsigned int) = &::p_uvec_set_count_char;
char (*_121)(const UVec_char*) = &::uvec_last_char;
UVec_char (*_122)(const UVec_char*, unsigned int) = &::uvec_view_from_char;
void (*_123)(UVec_char*) = &::uvec_deinit_char;
UVec_char (*_124)(UVec_char*) = &::uvec_move_char;
uvec_ret (*_125)(UVec_char*, unsigned int) = &::uvec_expand_char;
uvec_ret (*_126)(UVec_char*, const UVec_char*) = &::uvec_append_char;
uvec_ret (*_127)(UVec_char*, const char*, unsigned int) = &::uvec_append_array_char;
uvec_ret (*_128)(UVec_char*, unsigned int, char) = &::uvec_insert_at_char;
void (*_129)(UVec_char*, unsigned int) = &::uvec_unordered_remove_at_char;
void (*_130)(UVec_char*) = &::uvec_clear_char;
UVec_Loop_char (*_131)(const UVec_char*) = &::p_uvec_loop_init_char;
UVec_Loop_char (*_132)(const UVec_char*) = &::p_uvec_loop_reverse_init_char;
bool (*_133)(const UVec_char*, char) = &::uvec_contains_char;
void (*_134)(UVec_char*) = &::uvec_sort_char;
bool (*_135)(const UVec_char*, char) = &::uvec_sorted_contains_char;
UVec_ulib_byte (*_136)() = &::uvec_ulib_byte;
UVec_ulib_byte (*_137)(unsigned char*, unsigned int) = &::uvec_assign_ulib_byte;
UVec_ulib_byte (*_138)(unsigned char*, unsigned int) = &::uvec_wrap_ulib_byte;
unsigned char* (*_139)(const UVec_ulib_byte*) = &::uvec_data_ulib_byte;
unsigned int (*_140)(const UVec_ulib_byte*) = &::uvec_size_ulib_byte;
unsigned int (*_141)(const UVec_ulib_byte*) = &::uvec_count_ulib_byte;
void (*_142)(UVec_ulib_byte*, unsigned int) = &::p_uvec_set_count_ulib_byte;
unsigned char (*_143)(const UVec_ulib_byte*) = &::uvec_last_ulib_byte;
UVec_ulib_byte (*_144)(const UVec_ulib_byte*, unsigned int) = &::uvec_view_from_ulib_byte;
void (*_145)(UVec_ulib_byte*) = &::uvec_deinit_ulib_byte;
UVec_ulib_byte (*_146)(UVec_ulib_byte*) = &::uvec_move_ulib_byte;
uvec_ret (*_147)(UVec_ulib_byte*, unsigned int) = &::uvec_expand_ulib_byte;
uvec_ret (*_148)(UVec_ulib_byte*, const UVec_ulib_byte*) = &::uvec_append_ulib_byte;
uvec_ret (*_149)(UVec_ulib_byte*, const unsigned char*, unsigned int) = &::uvec_append_array_ulib_byte;
uvec_ret (*_150)(UVec_ulib_byte*, unsigned int, unsigned char) = &::uvec_insert_at_ulib_byte;
void (*_151)(UVec_ulib_byte*, unsigned int) = &::uvec_unordered_remove_at_ulib_byte;
void (*_152)(UVec_ulib_byte*) = &::uvec_clear_ulib_byte;
UVec_Loop_ulib_byte (*_153)(const UVec_ulib_byte*) = &::p_uvec_loop_init_ulib_byte;
UVec_Loop_ulib_byte (*_154)(const UVec_ulib_byte*) = &::p_uvec_loop_reverse_init_ulib_byte;
bool (*_155)(const UVec_ulib_byte*, unsigned char) = &::uvec_contains_ulib_byte;
void (*_156)(UVec_ulib_byte*) = &::uvec_sort_ulib_byte;
bool (*_157)(const UVec_ulib_byte*, unsigned char) = &::uvec_sorted_contains_ulib_byte;
UVec_ulib_int (*_158)() = &::uvec_ulib_int;
UVec_ulib_int (*_159)(int*, unsigned int) = &::uvec_assign_ulib_int;
UVec_ulib_int (*_160)(int*, unsigned int) = &::uvec_wrap_ulib_int;
int* (*_161)(const UVec_ulib_int*) = &::uvec_data_ulib_int;
unsigned int (*_162)(const UVec_ulib_int*) = &::uvec_size_ulib_int;
unsigned int (*_163)(const UVec_ulib_int*) = &::uvec_count_ulib_int;
void (*_164)(UVec_ulib_int*, unsigned int) = &::p_uvec_set_count_ulib_int;
int (*_165)(const UVec_ulib_int*) = &::uvec_last_ulib_int;
UVec_ulib_int (*_166)(const UVec_ulib_int*, unsigned int) = &::uvec_view_from_ulib_int;
void (*_167)(UVec_ulib_int*) = &::uvec_deinit_ulib_int;
UVec_ulib_int (*_168)(UVec_ulib_int*) = &::uvec_move_ulib_int;
uvec_ret (*_169)(UVec_ulib_int*, unsigned int) = &::uvec_expand_ulib_int;
uvec_ret (*_170)(UVec_ulib_int*, const UVec_ulib_int*) = &::uvec_append_ulib_int;
uvec_ret (*_171)(UVec_ulib_int*, const int*, unsigned int) = &::uvec_append_array_ulib_int;
uvec_ret (*_172)(UVec_ulib_int*, unsigned int, int) = &::uvec_insert_at_ulib_int;
void (*_173)(UVec_ulib_int*, unsigned int) = &::uvec_unordered_remove_at_ulib_int;
void (*_174)(UVec_ulib_int*) = &::uvec_clear_ulib_int;
UVec_Loop_ulib_int (*_175)(const UVec_ulib_int*) = &::p_uvec_loop_init_ulib_int;
UVec_Loop_ulib_int (*_176)(const UVec_ulib_int*) = &::p_uvec_loop_reverse_init_ulib_int;
bool (*_177)(const UVec_ulib_int*, int) = &::uvec_contains_ulib_int;
void (*_178)(UVec_ulib_int*) = &::uvec_sort_ulib_int;
bool (*_179)(const UVec_ulib_int*, int) = &::uvec_sorted_contains_ulib_int;
UVec_ulib_uint (*_180)() = &::uvec_ulib_uint;
UVec_ulib_uint (*_181)(unsigned int*, unsigned int) = &::uvec_assign_ulib_uint;
UVec_ulib_uint (*_182)(unsigned int*, unsigned int) = &::uvec_wrap_ulib_uint;
unsigned int* (*_183)(const UVec_ulib_uint*) = &::uvec_data_ulib_uint;
unsigned int (*_184)(const UVec_ulib_uint*) = &::uvec_size_ulib_uint;
unsigned int (*_185)(const UVec_ulib_uint*) = &::uvec_count_ulib_uint;
void (*_186)(UVec_ulib_uint*, unsigned int) = &::p_uvec_set_count_ulib_uint;
unsigned int (*_187)(const UVec_ulib_uint*) = &::uvec_last_ulib_uint;
UVec_ulib_uint (*_188)(const UVec_ulib_uint*, unsigned int) = &::uvec_view_from_ulib_uint;
void (*_189)(UVec_ulib_uint*) = &::uvec_deinit_ulib_uint;
UVec_ulib_uint (*_190)(UVec_ulib_uint*) = &::uvec_move_ulib_uint;
uvec_ret (*_191)(UVec_ulib_uint*, unsigned int) = &::uvec_expand_ulib_uint;
uvec_ret (*_192)(UVec_ulib_uint*, const UVec_ulib_uint*) = &::uvec_append_ulib_uint;
uvec_ret (*_193)(UVec_ulib_uint*, const unsigned int*, unsigned int) = &::uvec_append_array_ulib_uint;
uvec_ret (*_194)(UVec_ulib_uint*, unsigned int, unsigned int) = &::uvec_insert_at_ulib_uint;
void (*_195)(UVec_ulib_uint*, unsigned int) = &::uvec_unordered_remove_at_ulib_uint;
void (*_196)(UVec_ulib_uint*) = &::uvec_clear_ulib_uint;
UVec_Loop_ulib_uint (*_197)(const UVec_ulib_uint*) = &::p_uvec_loop_init_ulib_uint;
UVec_Loop_ulib_uint (*_198)(const UVec_ulib_uint*) = &::p_uvec_loop_reverse_init_ulib_uint;
bool (*_199)(const UVec_ulib_uint*, unsigned int) = &::uvec_contains_ulib_uint;
void (*_200)(UVec_ulib_uint*) = &::uvec_sort_ulib_uint;
bool (*_201)(const UVec_ulib_uint*, unsigned int) = &::uvec_sorted_contains_ulib_uint;
UVec_ulib_float (*_202)() = &::uvec_ulib_float;
UVec_ulib_float (*_203)(double*, unsigned int) = &::uvec_assign_ulib_float;
UVec_ulib_float (*_204)(double*, unsigned int) = &::uvec_wrap_ulib_float;
double* (*_205)(const UVec_ulib_float*) = &::uvec_data_ulib_float;
unsigned int (*_206)(const UVec_ulib_float*) = &::uvec_size_ulib_float;
unsigned int (*_207)(const UVec_ulib_float*) = &::uvec_count_ulib_float;
void (*_208)(UVec_ulib_float*, unsigned int) = &::p_uvec_set_count_ulib_float;
double (*_209)(const UVec_ulib_float*) = &::uvec_last_ulib_float;
UVec_ulib_float (*_210)(const UVec_ulib_float*, unsigned int) = &::uvec_view_from_ulib_float;
void (*_211)(UVec_ulib_float*) = &::uvec_deinit_ulib_float;
UVec_ulib_float (*_212)(UVec_ulib_float*) = &::uvec_move_ulib_float;
uvec_ret (*_213)(UVec_ulib_float*, unsigned int) = &::uvec_expand_ulib_float;
uvec_ret (*_214)(UVec_ulib_float*, const UVec_ulib_float*) = &::uvec_append_ulib_float;
uvec_ret (*_215)(UVec_ulib_float*, const double*, unsigned int) = &::uvec_append_array_ulib_float;
uvec_ret (*_216)(UVec_ulib_float*, unsigned int, double) = &::uvec_insert_at_ulib_float;
void (*_217)(UVec_ulib_float*, unsigned int) = &::uvec_unordered_remove_at_ulib_float;
void (*_218)(UVec_ulib_float*) = &::uvec_clear_ulib_float;
UVec_Loop_ulib_float (*_219)(const UVec_ulib_float*) = &::p_uvec_loop_init_ulib_float;
UVec_Loop_ulib_float (*_220)(const UVec_ulib_float*) = &::p_uvec_loop_reverse_init_ulib_float;
bool (*_221)(const UVec_ulib_float*, double) = &::uvec_contains_ulib_float;
void (*_222)(UVec_ulib_float*) = &::uvec_sort_ulib_float;
bool (*_223)(const UVec_ulib_float*, double) = &::uvec_sorted_contains_ulib_float;
UVec_ulib_ptr (*_224)() = &::uvec_ulib_ptr;
UVec_ulib_ptr (*_225)(void**, unsigned int) = &::uvec_assign_ulib_ptr;
UVec_ulib_ptr (*_226)(void**, unsigned int) = &::uvec_wrap_ulib_ptr;
void** (*_227)(const UVec_ulib_ptr*) = &::uvec_data_ulib_ptr;
unsigned int (*_228)(const UVec_ulib_ptr*) = &::uvec_size_ulib_ptr;
unsigned int (*_229)(const UVec_ulib_ptr*) = &::uvec_count_ulib_ptr;
void (*_230)(UVec_ulib_ptr*, unsigned int) = &::p_uvec_set_count_ulib_ptr;
void* (*_231)(const UVec_ulib_ptr*) = &::uvec_last_ulib_ptr;
UVec_ulib_ptr (*_232)(const UVec_ulib_ptr*, unsigned int) = &::uvec_view_from_ulib_ptr;
void (*_233)(UVec_ulib_ptr*) = &::uvec_deinit_ulib_ptr;
UVec_ulib_ptr (*_234)(UVec_ulib_ptr*) = &::uvec_move_ulib_ptr;
uvec_ret (*_235)(UVec_ulib_ptr*, unsigned int) = &::uvec_expand_ulib_ptr;
uvec_ret (*_236)(UVec_ulib_ptr*, const UVec_ulib_ptr*) = &::uvec_append_ulib_ptr;
uvec_ret (*_237)(UVec_ulib_ptr*, const void**, unsigned int) = &::uvec_append_array_ulib_ptr;
uvec_ret (*_238)(UVec_ulib_ptr*, unsigned int, void*) = &::uvec_insert_at_ulib_ptr;
void (*_239)(UVec_ulib_ptr*, unsigned int) = &::uvec_unordered_remove_at_ulib_ptr;
void (*_240)(UVec_ulib_ptr*) = &::uvec_clear_ulib_ptr;
UVec_Loop_ulib_ptr (*_241)(const UVec_ulib_ptr*) = &::p_uvec_loop_init_ulib_ptr;
UVec_Loop_ulib_ptr (*_242)(const UVec_ulib_ptr*) = &::p_uvec_loop_reverse_init_ulib_ptr;
bool (*_243)(const UVec_ulib_ptr*, void*) = &::uvec_contains_ulib_ptr;
void (*_244)(UVec_ulib_ptr*) = &::uvec_sort_ulib_ptr;
bool (*_245)(const UVec_ulib_ptr*, void*) = &::uvec_sorted_contains_ulib_ptr;
UVec_UString (*_246)() = &::uvec_UString;
UVec_UString (*_247)(UString*, unsigned int) = &::uvec_assign_UString;
UVec_UString (*_248)(UString*, unsigned int) = &::uvec_wrap_UString;
UString* (*_249)(const UVec_UString*) = &::uvec_data_UString;
unsigned int (*_250)(const UVec_UString*) = &::uvec_size_UString;
unsigned int (*_251)(const UVec_UString*) = &::uvec_count_UString;
void (*_252)(UVec_UString*, unsigned int) = &::p_uvec_set_count_UString;
UString (*_253)(const UVec_UString*) = &::uvec_last_UString;
UVec_UString (*_254)(const UVec_UString*, unsigned int) = &::uvec_view_from_UString;
void (*_255)(UVec_UString*) = &::uvec_deinit_UString;
UVec_UString (*_256)(UVec_UString*) = &::uvec_move_UString;
uvec_ret (*_257)(UVec_UString*, unsigned int) = &::uvec_expand_UString;
uvec_ret (*_258)(UVec_UString*, const UVec_UString*) = &::uvec_append_UString;
uvec_ret (*_259)(UVec_UString*, const UString*, unsigned int) = &::uvec_append_array_UString;
uvec_ret (*_260)(UVec_UString*, unsigned int, UString) = &::uvec_insert_at_UString;
void (*_261)(UVec_UString*, unsigned int) = &::uvec_unordered_remove_at_UString;
void (*_262)(UVec_UString*) = &::uvec_clear_UString;
UVec_Loop_UString (*_263)(const UVec_UString*) = &::p_uvec_loop_init_UString;
UVec_Loop_UString (*_264)(const UVec_UString*) = &::p_uvec_loop_reverse_init_UString;
bool (*_265)(const UVec_UString*, UString) = &::uvec_contains_UString;
void (*_266)(UVec_UString*) = &::uvec_sort_UString;
bool (*_267)(const UVec_UString*, UString) = &::uvec_sorted_contains_UString;
UTime& (UTime::*_268)(UTime&&) = &UTime::operator=;
void (*_269)(UTime*, int, unsigned int) = &::utime_normalize_to_utc;
bool (*_270)(long long) = &::utime_is_leap_year;
unsigned int (*_271)(long long, unsigned int) = &::utime_days_in_month;
UIStream& (UIStream::*_272)(UIStream&&) = &UIStream::operator=;
UOStream& (UOStream::*_273)(UOStream&&) = &UOStream::operator=;
UIStream (*_274)(void*, ustream_ret (*)(void*, void*, unsigned long long, unsigned long long*), ustream_ret (*)(void*), ustream_ret (*)(void*)) = &::uistream;
unsigned char (*_275)(CowlPrimitiveType) = &::cowl_primitive_flags_from_type;
bool (*_276)(unsigned char, CowlPrimitiveType) = &::cowl_primitive_flags_has_type;
CowlIterator& (CowlIterator::*_277)(CowlIterator&&) = &CowlIterator::operator=;
CowlFilter& (CowlFilter::*_278)(CowlFilter&&) = &CowlFilter::operator=;
bool (*_279)(const CowlIterator*, void*) = &::cowl_iterator_call;
void* (*_280)(CowlObjectType, void*, void*) = &::cowl_get_impl_1_opt;
void* (*_281)(CowlObjectType, void*, CowlVector*) = &::cowl_get_impl_1_annot;
void* (*_282)(CowlObjectType, void*) = &::cowl_get_impl_1;
void* (*_283)(CowlObjectType, void*, void*, void*) = &::cowl_get_impl_2_opt;
void* (*_284)(CowlObjectType, void*, void*, CowlVector*) = &::cowl_get_impl_2_annot;
void* (*_285)(CowlObjectType, void*, void*) = &::cowl_get_impl_2;
void* (*_286)(CowlObjectType, void*, void*, void*, void*) = &::cowl_get_impl_3_opt;
void* (*_287)(CowlObjectType, void*, void*, void*, CowlVector*) = &::cowl_get_impl_3_annot;
void* (*_288)(CowlObjectType, void*, void*, void*) = &::cowl_get_impl_3;
void* (*_289)(CowlObjectType, void*, unsigned int, void*) = &::cowl_get_impl_1_uint_opt;
void* (*_290)(CowlObjectType, void*, unsigned int) = &::cowl_get_impl_1_uint;
void* (*_291)(CowlObjectType, void*, void*, unsigned int, void*) = &::cowl_get_impl_2_uint_opt;
void* (*_292)(CowlObjectType, void*, void*, unsigned int) = &::cowl_get_impl_2_uint;
CowlAnnotAssertAxiom* (*_293)(CowlAnnotProp*, void*, void*, CowlVector*) = &::cowl_annot_assert_axiom;
CowlAnnotProp* (*_294)(CowlAnnotAssertAxiom*) = &::cowl_annot_assert_axiom_get_prop;
CowlAnnotValue* (*_295)(CowlAnnotAssertAxiom*) = &::cowl_annot_assert_axiom_get_subject;
CowlAnnotValue* (*_296)(CowlAnnotAssertAxiom*) = &::cowl_annot_assert_axiom_get_value;
CowlAnnotProp* (*_297)(CowlIRI*) = &::cowl_annot_prop;
CowlAnnotProp* (*_298)(UString) = &::cowl_annot_prop_from_string;
CowlIRI* (*_299)(CowlAnnotProp*) = &::cowl_annot_prop_get_iri;
CowlAnnotPropDomainAxiom* (*_300)(CowlAnnotProp*, CowlIRI*, CowlVector*) = &::cowl_annot_prop_domain_axiom;
CowlAnnotProp* (*_301)(CowlAnnotPropDomainAxiom*) = &::cowl_annot_prop_domain_axiom_get_prop;
CowlIRI* (*_302)(CowlAnnotPropDomainAxiom*) = &::cowl_annot_prop_domain_axiom_get_domain;
CowlAnnotPropRangeAxiom* (*_303)(CowlAnnotProp*, CowlIRI*, CowlVector*) = &::cowl_annot_prop_range_axiom;
CowlAnnotProp* (*_304)(CowlAnnotPropRangeAxiom*) = &::cowl_annot_prop_range_axiom_get_prop;
CowlIRI* (*_305)(CowlAnnotPropRangeAxiom*) = &::cowl_annot_prop_range_axiom_get_range;
CowlAnnotation* (*_306)(CowlAnnotProp*, void*, CowlVector*) = &::cowl_annotation;
CowlAnnotProp* (*_307)(CowlAnnotation*) = &::cowl_annotation_get_prop;
CowlAnnotValue* (*_308)(CowlAnnotation*) = &::cowl_annotation_get_value;
CowlVector* (*_309)(CowlAnnotation*) = &::cowl_annotation_get_annot;
bool (*_310)(void*) = &::cowl_primitive_is_entity;
CowlAxiomType (*_311)(void*) = &::cowl_axiom_get_type;
CowlVector* (*_312)(void*) = &::cowl_axiom_get_annot;
unsigned long long (*_313)(CowlAxiomType) = &::cowl_axiom_flags_from_type;
bool (*_314)(unsigned long long, CowlAxiomType) = &::cowl_axiom_flags_has_type;
bool (*_315)(unsigned long long) = &::cowl_axiom_flags_has_all_types;
bool (*_316)(unsigned long long) = &::cowl_axiom_flags_has_no_types;
struct p_uvec_sizing_CowlObjectPtr& (p_uvec_sizing_CowlObjectPtr::*_317)(struct p_uvec_sizing_CowlObjectPtr&&) = &p_uvec_sizing_CowlObjectPtr::operator=;
struct p_uvec_large_CowlObjectPtr& (p_uvec_large_CowlObjectPtr::*_318)(struct p_uvec_large_CowlObjectPtr&&) = &p_uvec_large_CowlObjectPtr::operator=;
UVec_CowlObjectPtr& (UVec_CowlObjectPtr::*_319)(UVec_CowlObjectPtr&&) = &UVec_CowlObjectPtr::operator=;
UVec_Loop_CowlObjectPtr& (UVec_Loop_CowlObjectPtr::*_320)(UVec_Loop_CowlObjectPtr&&) = &UVec_Loop_CowlObjectPtr::operator=;
UVec_CowlObjectPtr (*_321)() = &::uvec_CowlObjectPtr;
UVec_CowlObjectPtr (*_322)(void**, unsigned int) = &::uvec_assign_CowlObjectPtr;
UVec_CowlObjectPtr (*_323)(void**, unsigned int) = &::uvec_wrap_CowlObjectPtr;
void** (*_324)(const UVec_CowlObjectPtr*) = &::uvec_data_CowlObjectPtr;
unsigned int (*_325)(const UVec_CowlObjectPtr*) = &::uvec_size_CowlObjectPtr;
unsigned int (*_326)(const UVec_CowlObjectPtr*) = &::uvec_count_CowlObjectPtr;
void (*_327)(UVec_CowlObjectPtr*, unsigned int) = &::p_uvec_set_count_CowlObjectPtr;
void* (*_328)(const UVec_CowlObjectPtr*) = &::uvec_last_CowlObjectPtr;
UVec_CowlObjectPtr (*_329)(const UVec_CowlObjectPtr*, unsigned int) = &::uvec_view_from_CowlObjectPtr;
void (*_330)(UVec_CowlObjectPtr*) = &::uvec_deinit_CowlObjectPtr;
UVec_CowlObjectPtr (*_331)(UVec_CowlObjectPtr*) = &::uvec_move_CowlObjectPtr;
uvec_ret (*_332)(UVec_CowlObjectPtr*, unsigned int) = &::uvec_expand_CowlObjectPtr;
uvec_ret (*_333)(UVec_CowlObjectPtr*, const UVec_CowlObjectPtr*) = &::uvec_append_CowlObjectPtr;
uvec_ret (*_334)(UVec_CowlObjectPtr*, const void**, unsigned int) = &::uvec_append_array_CowlObjectPtr;
uvec_ret (*_335)(UVec_CowlObjectPtr*, unsigned int, void*) = &::uvec_insert_at_CowlObjectPtr;
void (*_336)(UVec_CowlObjectPtr*, unsigned int) = &::uvec_unordered_remove_at_CowlObjectPtr;
void (*_337)(UVec_CowlObjectPtr*) = &::uvec_clear_CowlObjectPtr;
UVec_Loop_CowlObjectPtr (*_338)(const UVec_CowlObjectPtr*) = &::p_uvec_loop_init_CowlObjectPtr;
UVec_Loop_CowlObjectPtr (*_339)(const UVec_CowlObjectPtr*) = &::p_uvec_loop_reverse_init_CowlObjectPtr;
bool (*_340)(const UVec_CowlObjectPtr*, void*) = &::uvec_contains_CowlObjectPtr;
unsigned int (*_341)(CowlVector*) = &::cowl_vector_count;
void* (*_342)(CowlVector*, unsigned int) = &::cowl_vector_get_item;
bool (*_343)(CowlVector*, void*) = &::cowl_vector_contains;
CowlAxiomFilter& (CowlAxiomFilter::*_344)(CowlAxiomFilter&&) = &CowlAxiomFilter::operator=;
CowlAxiomFilter (*_345)(unsigned long long) = &::cowl_axiom_filter;
void (*_346)(CowlAxiomFilter*) = &::cowl_axiom_filter_deinit;
void (*_347)(CowlAxiomFilter*, CowlAxiomType) = &::cowl_axiom_filter_add_type;
void (*_348)(CowlAxiomFilter*, CowlAxiomType) = &::cowl_axiom_filter_remove_type;
cowl_ret (*_349)(CowlAxiomFilter*, void*) = &::cowl_axiom_filter_add_primitive;
void (*_350)(CowlAxiomFilter*, void*) = &::cowl_axiom_filter_remove_primitive;
void (*_351)(CowlAxiomFilter*, CowlFilter) = &::cowl_axiom_filter_set_closure;
CowlClass* (*_352)(CowlIRI*) = &::cowl_class;
CowlClass* (*_353)(UString) = &::cowl_class_from_string;
CowlIRI* (*_354)(CowlClass*) = &::cowl_class_get_iri;
CowlClsAssertAxiom* (*_355)(void*, void*, CowlVector*) = &::cowl_cls_assert_axiom;
CowlClsExp* (*_356)(CowlClsAssertAxiom*) = &::cowl_cls_assert_axiom_get_cls_exp;
CowlIndividual* (*_357)(CowlClsAssertAxiom*) = &::cowl_cls_assert_axiom_get_ind;
CowlClsExpType (*_358)(void*) = &::cowl_cls_exp_get_type;
CowlErrorLoc& (CowlErrorLoc::*_359)(CowlErrorLoc&&) = &CowlErrorLoc::operator=;
CowlError& (CowlError::*_360)(CowlError&&) = &CowlError::operator=;
CowlSyntaxError& (CowlSyntaxError::*_361)(CowlSyntaxError&&) = &CowlSyntaxError::operator=;
CowlErrorHandler& (CowlErrorHandler::*_362)(CowlErrorHandler&&) = &CowlErrorHandler::operator=;
CowlImportLoader& (CowlImportLoader::*_363)(CowlImportLoader&&) = &CowlImportLoader::operator=;
CowlReader& (CowlReader::*_364)(CowlReader&&) = &CowlReader::operator=;
CowlOntologyId& (CowlOntologyId::*_365)(CowlOntologyId&&) = &CowlOntologyId::operator=;
CowlOntologyId (*_366)() = &::cowl_ontology_id_anonymous;
CowlOntologyHeader& (CowlOntologyHeader::*_367)(CowlOntologyHeader&&) = &CowlOntologyHeader::operator=;
CowlOntologyHeader (*_368)() = &::cowl_ontology_header_empty;
CowlStreamWriter& (CowlStreamWriter::*_369)(CowlStreamWriter&&) = &CowlStreamWriter::operator=;
CowlWriter& (CowlWriter::*_370)(CowlWriter&&) = &CowlWriter::operator=;
bool (*_371)(const CowlWriter*) = &::cowl_writer_can_write_stream;
bool (*_372)(const CowlWriter*) = &::cowl_writer_can_write_object;
bool (*_373)(const CowlWriter*) = &::cowl_writer_can_write_ontology;
ustream_ret (*_374)(UOStream*, const UString*) = &::cowl_write_ustring;
ustream_ret (*_375)(UOStream*, const char*) = &::cowl_write_cstring;
CowlCardType (*_376)(CowlDataCard*) = &::cowl_data_card_get_type;
CowlDataPropExp* (*_377)(CowlDataCard*) = &::cowl_data_card_get_prop;
unsigned int (*_378)(CowlDataCard*) = &::cowl_data_card_get_cardinality;
CowlDataCompl* (*_379)(void*) = &::cowl_data_compl;
CowlDataRange* (*_380)(CowlDataCompl*) = &::cowl_data_compl_get_operand;
CowlDataHasValue* (*_381)(void*, CowlLiteral*) = &::cowl_data_has_value;
CowlDataPropExp* (*_382)(CowlDataHasValue*) = &::cowl_data_has_value_get_prop;
CowlLiteral* (*_383)(CowlDataHasValue*) = &::cowl_data_has_value_get_value;
CowlDataOneOf* (*_384)(CowlVector*) = &::cowl_data_one_of;
CowlVector* (*_385)(CowlDataOneOf*) = &::cowl_data_one_of_get_values;
CowlDataProp* (*_386)(CowlIRI*) = &::cowl_data_prop;
CowlDataProp* (*_387)(UString) = &::cowl_data_prop_from_string;
CowlIRI* (*_388)(CowlDataProp*) = &::cowl_data_prop_get_iri;
CowlDataPropAssertAxiom* (*_389)(void*, void*, CowlLiteral*, CowlVector*) = &::cowl_data_prop_assert_axiom;
CowlDataPropAssertAxiom* (*_390)(void*, void*, CowlLiteral*, CowlVector*) = &::cowl_neg_data_prop_assert_axiom;
bool (*_391)(CowlDataPropAssertAxiom*) = &::cowl_data_prop_assert_axiom_is_negative;
CowlDataPropExp* (*_392)(CowlDataPropAssertAxiom*) = &::cowl_data_prop_assert_axiom_get_prop;
CowlIndividual* (*_393)(CowlDataPropAssertAxiom*) = &::cowl_data_prop_assert_axiom_get_subject;
CowlLiteral* (*_394)(CowlDataPropAssertAxiom*) = &::cowl_data_prop_assert_axiom_get_object;
CowlDataPropDomainAxiom* (*_395)(void*, void*, CowlVector*) = &::cowl_data_prop_domain_axiom;
CowlDataPropExp* (*_396)(CowlDataPropDomainAxiom*) = &::cowl_data_prop_domain_axiom_get_prop;
CowlClsExp* (*_397)(CowlDataPropDomainAxiom*) = &::cowl_data_prop_domain_axiom_get_domain;
CowlDataProp* (*_398)(void*) = &::cowl_data_prop_exp_get_prop;
CowlDataPropRangeAxiom* (*_399)(void*, void*, CowlVector*) = &::cowl_data_prop_range_axiom;
CowlDataPropExp* (*_400)(CowlDataPropRangeAxiom*) = &::cowl_data_prop_range_axiom_get_prop;
CowlDataRange* (*_401)(CowlDataPropRangeAxiom*) = &::cowl_data_prop_range_axiom_get_range;
CowlQuantType (*_402)(CowlDataQuant*) = &::cowl_data_quant_get_type;
CowlDataPropExp* (*_403)(CowlDataQuant*) = &::cowl_data_quant_get_prop;
CowlDataRangeType (*_404)(void*) = &::cowl_data_range_get_type;
CowlDatatype* (*_405)(CowlIRI*) = &::cowl_datatype;
CowlDatatype* (*_406)(UString) = &::cowl_datatype_from_string;
CowlIRI* (*_407)(CowlDatatype*) = &::cowl_datatype_get_iri;
CowlDatatypeDefAxiom* (*_408)(CowlDatatype*, void*, CowlVector*) = &::cowl_datatype_def_axiom;
CowlDatatype* (*_409)(CowlDatatypeDefAxiom*) = &::cowl_datatype_def_axiom_get_datatype;
CowlDataRange* (*_410)(CowlDatatypeDefAxiom*) = &::cowl_datatype_def_axiom_get_range;
CowlDatatypeRestr* (*_411)(CowlDatatype*, CowlVector*) = &::cowl_datatype_restr;
CowlDatatype* (*_412)(CowlDatatypeRestr*) = &::cowl_datatype_restr_get_datatype;
CowlVector* (*_413)(CowlDatatypeRestr*) = &::cowl_datatype_restr_get_restrictions;
CowlDeclAxiom* (*_414)(void*, CowlVector*) = &::cowl_decl_axiom;
CowlEntity* (*_415)(CowlDeclAxiom*) = &::cowl_decl_axiom_get_entity;
CowlDisjUnionAxiom* (*_416)(CowlClass*, CowlVector*, CowlVector*) = &::cowl_disj_union_axiom;
CowlClass* (*_417)(CowlDisjUnionAxiom*) = &::cowl_disj_union_axiom_get_class;
CowlVector* (*_418)(CowlDisjUnionAxiom*) = &::cowl_disj_union_axiom_get_disjoints;
CowlFacetRestr* (*_419)(CowlIRI*, CowlLiteral*) = &::cowl_facet_restr;
CowlIRI* (*_420)(CowlFacetRestr*) = &::cowl_facet_restr_get_facet;
CowlLiteral* (*_421)(CowlFacetRestr*) = &::cowl_facet_restr_get_value;
CowlFuncDataPropAxiom* (*_422)(void*, CowlVector*) = &::cowl_func_data_prop_axiom;
CowlDataPropExp* (*_423)(CowlFuncDataPropAxiom*) = &::cowl_func_data_prop_axiom_get_prop;
CowlHasKeyAxiom* (*_424)(void*, CowlVector*, CowlVector*, CowlVector*) = &::cowl_has_key_axiom;
CowlClsExp* (*_425)(CowlHasKeyAxiom*) = &::cowl_has_key_axiom_get_cls_exp;
CowlVector* (*_426)(CowlHasKeyAxiom*) = &::cowl_has_key_axiom_get_obj_props;
CowlVector* (*_427)(CowlHasKeyAxiom*) = &::cowl_has_key_axiom_get_data_props;
bool (*_428)(void*) = &::cowl_individual_is_named;
CowlInvObjProp* (*_429)(CowlObjProp*) = &::cowl_inv_obj_prop;
CowlObjProp* (*_430)(CowlInvObjProp*) = &::cowl_inv_obj_prop_get_prop;
CowlInvObjPropAxiom* (*_431)(void*, void*, CowlVector*) = &::cowl_inv_obj_prop_axiom;
CowlObjPropExp* (*_432)(CowlInvObjPropAxiom*) = &::cowl_inv_obj_prop_axiom_get_first_prop;
CowlObjPropExp* (*_433)(CowlInvObjPropAxiom*) = &::cowl_inv_obj_prop_axiom_get_second_prop;
cowl_ret (*_434)(CowlString*, int*, unsigned int) = &::cowl_string_to_int;
cowl_ret (*_435)(CowlString*, unsigned int*, unsigned int) = &::cowl_string_to_uint;
cowl_ret (*_436)(CowlString*, double*) = &::cowl_string_to_float;
bool (*_437)(CowlIRI*) = &::cowl_iri_has_rem;
CowlIStreamHandlers& (CowlIStreamHandlers::*_438)(CowlIStreamHandlers&&) = &CowlIStreamHandlers::operator=;
CowlNamedInd* (*_439)(CowlIRI*) = &::cowl_named_ind;
CowlNamedInd* (*_440)(UString) = &::cowl_named_ind_from_string;
CowlIRI* (*_441)(CowlNamedInd*) = &::cowl_named_ind_get_iri;
CowlNAryBool* (*_442)(CowlNAryType, CowlVector*) = &::cowl_nary_bool;
CowlNAryType (*_443)(CowlNAryBool*) = &::cowl_nary_bool_get_type;
CowlVector* (*_444)(CowlNAryBool*) = &::cowl_nary_bool_get_operands;
CowlNAryClsAxiom* (*_445)(CowlNAryAxiomType, CowlVector*, CowlVector*) = &::cowl_nary_cls_axiom;
CowlNAryAxiomType (*_446)(CowlNAryClsAxiom*) = &::cowl_nary_cls_axiom_get_type;
CowlVector* (*_447)(CowlNAryClsAxiom*) = &::cowl_nary_cls_axiom_get_classes;
CowlNAryData* (*_448)(CowlNAryType, CowlVector*) = &::cowl_nary_data;
CowlNAryType (*_449)(CowlNAryData*) = &::cowl_nary_data_get_type;
CowlVector* (*_450)(CowlNAryData*) = &::cowl_nary_data_get_operands;
CowlNAryDataPropAxiom* (*_451)(CowlNAryAxiomType, CowlVector*, CowlVector*) = &::cowl_nary_data_prop_axiom;
CowlNAryAxiomType (*_452)(CowlNAryDataPropAxiom*) = &::cowl_nary_data_prop_axiom_get_type;
CowlVector* (*_453)(CowlNAryDataPropAxiom*) = &::cowl_nary_data_prop_axiom_get_props;
CowlNAryIndAxiom* (*_454)(CowlNAryAxiomType, CowlVector*, CowlVector*) = &::cowl_nary_ind_axiom;
CowlNAryAxiomType (*_455)(CowlNAryIndAxiom*) = &::cowl_nary_ind_axiom_get_type;
CowlVector* (*_456)(CowlNAryIndAxiom*) = &::cowl_nary_ind_axiom_get_individuals;
CowlNAryObjPropAxiom* (*_457)(CowlNAryAxiomType, CowlVector*, CowlVector*) = &::cowl_nary_obj_prop_axiom;
CowlNAryAxiomType (*_458)(CowlNAryObjPropAxiom*) = &::cowl_nary_obj_prop_axiom_get_type;
CowlVector* (*_459)(CowlNAryObjPropAxiom*) = &::cowl_nary_obj_prop_axiom_get_props;
CowlCardType (*_460)(CowlObjCard*) = &::cowl_obj_card_get_type;
CowlObjPropExp* (*_461)(CowlObjCard*) = &::cowl_obj_card_get_prop;
unsigned int (*_462)(CowlObjCard*) = &::cowl_obj_card_get_cardinality;
CowlObjCompl* (*_463)(void*) = &::cowl_obj_compl;
CowlClsExp* (*_464)(CowlObjCompl*) = &::cowl_obj_compl_get_operand;
CowlObjHasSelf* (*_465)(void*) = &::cowl_obj_has_self;
CowlObjPropExp* (*_466)(CowlObjHasSelf*) = &::cowl_obj_has_self_get_prop;
CowlObjHasValue* (*_467)(void*, void*) = &::cowl_obj_has_value;
CowlObjPropExp* (*_468)(CowlObjHasValue*) = &::cowl_obj_has_value_get_prop;
CowlIndividual* (*_469)(CowlObjHasValue*) = &::cowl_obj_has_value_get_ind;
CowlObjOneOf* (*_470)(CowlVector*) = &::cowl_obj_one_of;
CowlVector* (*_471)(CowlObjOneOf*) = &::cowl_obj_one_of_get_inds;
CowlObjProp* (*_472)(CowlIRI*) = &::cowl_obj_prop;
CowlObjProp* (*_473)(UString) = &::cowl_obj_prop_from_string;
CowlIRI* (*_474)(CowlObjProp*) = &::cowl_obj_prop_get_iri;
CowlObjPropAssertAxiom* (*_475)(void*, void*, void*, CowlVector*) = &::cowl_obj_prop_assert_axiom;
CowlObjPropAssertAxiom* (*_476)(void*, void*, void*, CowlVector*) = &::cowl_neg_obj_prop_assert_axiom;
bool (*_477)(CowlObjPropAssertAxiom*) = &::cowl_obj_prop_assert_axiom_is_negative;
CowlObjPropExp* (*_478)(CowlObjPropAssertAxiom*) = &::cowl_obj_prop_assert_axiom_get_prop;
CowlIndividual* (*_479)(CowlObjPropAssertAxiom*) = &::cowl_obj_prop_assert_axiom_get_subject;
CowlIndividual* (*_480)(CowlObjPropAssertAxiom*) = &::cowl_obj_prop_assert_axiom_get_object;
CowlObjPropCharAxiom* (*_481)(CowlCharAxiomType, void*, CowlVector*) = &::cowl_obj_prop_char_axiom;
CowlCharAxiomType (*_482)(CowlObjPropCharAxiom*) = &::cowl_obj_prop_char_axiom_get_type;
CowlObjPropExp* (*_483)(CowlObjPropCharAxiom*) = &::cowl_obj_prop_char_axiom_get_prop;
CowlObjPropDomainAxiom* (*_484)(void*, void*, CowlVector*) = &::cowl_obj_prop_domain_axiom;
CowlObjPropExp* (*_485)(CowlObjPropDomainAxiom*) = &::cowl_obj_prop_domain_axiom_get_prop;
CowlClsExp* (*_486)(CowlObjPropDomainAxiom*) = &::cowl_obj_prop_domain_axiom_get_domain;
bool (*_487)(void*) = &::cowl_obj_prop_exp_is_inverse;
CowlObjPropRangeAxiom* (*_488)(void*, void*, CowlVector*) = &::cowl_obj_prop_range_axiom;
CowlObjPropExp* (*_489)(CowlObjPropRangeAxiom*) = &::cowl_obj_prop_range_axiom_get_prop;
CowlClsExp* (*_490)(CowlObjPropRangeAxiom*) = &::cowl_obj_prop_range_axiom_get_range;
CowlQuantType (*_491)(CowlObjQuant*) = &::cowl_obj_quant_get_type;
CowlObjPropExp* (*_492)(CowlObjQuant*) = &::cowl_obj_quant_get_prop;
bool (*_493)(CowlOntology*, CowlClass*, CowlIterator*, bool) = &::cowl_ontology_iterate_sub_classes;
bool (*_494)(CowlOntology*, CowlClass*, CowlIterator*, bool) = &::cowl_ontology_iterate_super_classes;
bool (*_495)(CowlOntology*, CowlClass*, CowlIterator*, bool) = &::cowl_ontology_iterate_eq_classes;
bool (*_496)(CowlOntology*, CowlClass*, CowlIterator*, bool) = &::cowl_ontology_iterate_disjoint_classes;
bool (*_497)(CowlOntology*, void*, CowlIterator*, bool) = &::cowl_ontology_iterate_types;
CowlOWLIRIVocab& (CowlOWLIRIVocab::*_498)(CowlOWLIRIVocab&&) = &CowlOWLIRIVocab::operator=;
CowlOWLClassVocab& (CowlOWLClassVocab::*_499)(CowlOWLClassVocab&&) = &CowlOWLClassVocab::operator=;
CowlOWLDatatypeVocab& (CowlOWLDatatypeVocab::*_500)(CowlOWLDatatypeVocab&&) = &CowlOWLDatatypeVocab::operator=;
CowlOWLObjPropVocab& (CowlOWLObjPropVocab::*_501)(CowlOWLObjPropVocab&&) = &CowlOWLObjPropVocab::operator=;
CowlOWLDataPropVocab& (CowlOWLDataPropVocab::*_502)(CowlOWLDataPropVocab&&) = &CowlOWLDataPropVocab::operator=;
CowlOWLAnnotPropVocab& (CowlOWLAnnotPropVocab::*_503)(CowlOWLAnnotPropVocab&&) = &CowlOWLAnnotPropVocab::operator=;
CowlOWLVocab& (CowlOWLVocab::*_504)(CowlOWLVocab&&) = &CowlOWLVocab::operator=;
CowlRDFIRIVocab& (CowlRDFIRIVocab::*_505)(CowlRDFIRIVocab&&) = &CowlRDFIRIVocab::operator=;
CowlRDFDatatypeVocab& (CowlRDFDatatypeVocab::*_506)(CowlRDFDatatypeVocab&&) = &CowlRDFDatatypeVocab::operator=;
CowlRDFVocab& (CowlRDFVocab::*_507)(CowlRDFVocab&&) = &CowlRDFVocab::operator=;
CowlRDFSIRIVocab& (CowlRDFSIRIVocab::*_508)(CowlRDFSIRIVocab&&) = &CowlRDFSIRIVocab::operator=;
CowlRDFSDatatypeVocab& (CowlRDFSDatatypeVocab::*_509)(CowlRDFSDatatypeVocab&&) = &CowlRDFSDatatypeVocab::operator=;
CowlRDFSAnnotPropVocab& (CowlRDFSAnnotPropVocab::*_510)(CowlRDFSAnnotPropVocab&&) = &CowlRDFSAnnotPropVocab::operator=;
CowlRDFSVocab& (CowlRDFSVocab::*_511)(CowlRDFSVocab&&) = &CowlRDFSVocab::operator=;
CowlSubAnnotPropAxiom* (*_512)(CowlAnnotProp*, CowlAnnotProp*, CowlVector*) = &::cowl_sub_annot_prop_axiom;
CowlAnnotProp* (*_513)(CowlSubAnnotPropAxiom*) = &::cowl_sub_annot_prop_axiom_get_sub;
CowlAnnotProp* (*_514)(CowlSubAnnotPropAxiom*) = &::cowl_sub_annot_prop_axiom_get_super;
CowlSubClsAxiom* (*_515)(void*, void*, CowlVector*) = &::cowl_sub_cls_axiom;
CowlClsExp* (*_516)(CowlSubClsAxiom*) = &::cowl_sub_cls_axiom_get_sub;
CowlClsExp* (*_517)(CowlSubClsAxiom*) = &::cowl_sub_cls_axiom_get_super;
CowlSubDataPropAxiom* (*_518)(void*, void*, CowlVector*) = &::cowl_sub_data_prop_axiom;
CowlDataPropExp* (*_519)(CowlSubDataPropAxiom*) = &::cowl_sub_data_prop_axiom_get_sub;
CowlDataPropExp* (*_520)(CowlSubDataPropAxiom*) = &::cowl_sub_data_prop_axiom_get_super;
CowlSubObjPropAxiom* (*_521)(void*, void*, CowlVector*) = &::cowl_sub_obj_prop_axiom;
void* (*_522)(CowlSubObjPropAxiom*) = &::cowl_sub_obj_prop_axiom_get_sub;
CowlObjPropExp* (*_523)(CowlSubObjPropAxiom*) = &::cowl_sub_obj_prop_axiom_get_super;
CowlIRI* (*_524)(CowlSymTable*, UString, UString) = &::cowl_sym_table_get_full_iri;
CowlIRI* (*_525)(CowlSymTable*, UString) = &::cowl_sym_table_parse_full_iri;
UHash_CowlObjectTable& (UHash_CowlObjectTable::*_526)(UHash_CowlObjectTable&&) = &UHash_CowlObjectTable::operator=;
UHash_Loop_CowlObjectTable& (UHash_Loop_CowlObjectTable::*_527)(UHash_Loop_CowlObjectTable&&) = &UHash_Loop_CowlObjectTable::operator=;
bool (*_528)(const UHash_CowlObjectTable*) = &::uhash_is_map_CowlObjectTable;
UHash_CowlObjectTable (*_529)(UHash_CowlObjectTable*) = &::uhash_move_CowlObjectTable;
unsigned int (*_530)(const UHash_CowlObjectTable*, unsigned int) = &::uhash_next_CowlObjectTable;
bool (*_531)(const UHash_CowlObjectTable*, const UHash_CowlObjectTable*) = &::uhset_equals_CowlObjectTable;
unsigned int (*_532)(const UHash_CowlObjectTable*) = &::p_uhash_occupied_CowlObjectTable;
unsigned int (*_533)(CowlTable*) = &::cowl_table_count;
void* (*_534)(CowlTable*, void*) = &::cowl_table_get_value;
void* (*_535)(CowlTable*) = &::cowl_table_get_any;
bool (*_536)(CowlTable*, void*) = &::cowl_table_contains;
CowlXSDIRIVocab& (CowlXSDIRIVocab::*_537)(CowlXSDIRIVocab&&) = &CowlXSDIRIVocab::operator=;
CowlXSDDatatypeVocab& (CowlXSDDatatypeVocab::*_538)(CowlXSDDatatypeVocab&&) = &CowlXSDDatatypeVocab::operator=;
CowlXSDVocab& (CowlXSDVocab::*_539)(CowlXSDVocab&&) = &CowlXSDVocab::operator=;
CowlVocab& (CowlVocab::*_540)(CowlVocab&&) = &CowlVocab::operator=;
