/* 
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IBlockchainReSTAPIApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Aggiungi un giocatore
        /// </summary>
        /// <remarks>
        /// Aggiungi un giocatore di una sessione di gioco quando è in preparazione.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="ID">Identificativo dell&#x27;asset a cui aggiungere un giocatore</param>
        /// <returns>string</returns>
        string AddPlayer(PlayerDTO body, string ID);

        /// <summary>
        /// Aggiungi un giocatore
        /// </summary>
        /// <remarks>
        /// Aggiungi un giocatore di una sessione di gioco quando è in preparazione.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="ID">Identificativo dell&#x27;asset a cui aggiungere un giocatore</param>
        /// <returns>ApiResponse of string</returns>
        ApiResponse<string> AddPlayerWithHttpInfo(PlayerDTO body, string ID);
        /// <summary>
        /// Cambia stato di un asset
        /// </summary>
        /// <remarks>
        /// Cambia lo stato di una sessione di gioco.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="ID">Identificativo dell&#x27;asset di cui cambiare lo stato</param>
        /// <returns>string</returns>
        string ChangeState(AssetDTO body, string ID);

        /// <summary>
        /// Cambia stato di un asset
        /// </summary>
        /// <remarks>
        /// Cambia lo stato di una sessione di gioco.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="ID">Identificativo dell&#x27;asset di cui cambiare lo stato</param>
        /// <returns>ApiResponse of string</returns>
        ApiResponse<string> ChangeStateWithHttpInfo(AssetDTO body, string ID);
        /// <summary>
        /// Crea un asset
        /// </summary>
        /// <remarks>
        /// Crea un nuovo asset che traccia una sessione di gioco.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>string</returns>
        string CreateAsset(AssetDTO body);

        /// <summary>
        /// Crea un asset
        /// </summary>
        /// <remarks>
        /// Crea un nuovo asset che traccia una sessione di gioco.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>ApiResponse of string</returns>
        ApiResponse<string> CreateAssetWithHttpInfo(AssetDTO body);
        /// <summary>
        /// Crea un evento
        /// </summary>
        /// <remarks>
        /// Aggiungi un evento per una sessione di gioco.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="ID">Identificativo dell&#x27;asset su cui registrare l&#x27;evento</param>
        /// <returns>string</returns>
        string CreateEvent(EventDTO body, string gameId, string eventId);

        /// <summary>
        /// Crea un evento
        /// </summary>
        /// <remarks>
        /// Aggiungi un evento per una sessione di gioco.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="ID">Identificativo dell&#x27;asset su cui registrare l&#x27;evento</param>
        /// <returns>ApiResponse of string</returns>
        ApiResponse<string> CreateEventWithHttpInfo(EventDTO body, string gameId, string eventId);
        /// <summary>
        /// Dettagli utente
        /// </summary>
        /// <remarks>
        /// Recupera i dettagli dell&#x27;utente che interagisce con l&#x27;API.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <returns>string</returns>
        string GetClientID();

        /// <summary>
        /// Dettagli utente
        /// </summary>
        /// <remarks>
        /// Recupera i dettagli dell&#x27;utente che interagisce con l&#x27;API.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of string</returns>
        ApiResponse<string> GetClientIDWithHttpInfo();
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <returns>string</returns>
        string Hello();

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of string</returns>
        ApiResponse<string> HelloWithHttpInfo();
        /// <summary>
        /// Leggi asset
        /// </summary>
        /// <remarks>
        /// Recupera tutti i dettagli di una sessione di gioco.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="ID">Identificativo dell&#x27;asset da leggere</param>
        /// <returns>string</returns>
        string ReadAsset(string ID);

        /// <summary>
        /// Leggi asset
        /// </summary>
        /// <remarks>
        /// Recupera tutti i dettagli di una sessione di gioco.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="ID">Identificativo dell&#x27;asset da leggere</param>
        /// <returns>ApiResponse of string</returns>
        ApiResponse<string> ReadAssetWithHttpInfo(string ID);
        /// <summary>
        /// Leggi evento
        /// </summary>
        /// <remarks>
        /// Recupera tutti i dettagli degli eventi inviati dall&#x27;utente.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="ID">Identificativo dell&#x27;asset da cui leggere gli eventi</param>
        /// <returns>string</returns>
        string ReadEvent(string ID);

        /// <summary>
        /// Leggi evento
        /// </summary>
        /// <remarks>
        /// Recupera tutti i dettagli degli eventi inviati dall&#x27;utente.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="ID">Identificativo dell&#x27;asset da cui leggere gli eventi</param>
        /// <returns>ApiResponse of string</returns>
        ApiResponse<string> ReadEventWithHttpInfo(string ID);
        /// <summary>
        /// Rimuovi un giocatore
        /// </summary>
        /// <remarks>
        /// Rimuovi un giocatore da una sessione di gioco in corso.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="ID">Identificativo dell&#x27;asset da cui rimuovere un giocatore</param>
        /// <returns>string</returns>
        string RemovePlayer(PlayerDTO body, string ID);

        /// <summary>
        /// Rimuovi un giocatore
        /// </summary>
        /// <remarks>
        /// Rimuovi un giocatore da una sessione di gioco in corso.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="ID">Identificativo dell&#x27;asset da cui rimuovere un giocatore</param>
        /// <returns>ApiResponse of string</returns>
        ApiResponse<string> RemovePlayerWithHttpInfo(PlayerDTO body, string ID);
        /// <summary>
        /// Aggiorna la descrizione dell&#x27;asset
        /// </summary>
        /// <remarks>
        /// Aggiorna la descrizione di un asset di una sessione di gioco.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="ID">Identificativo dell&#x27;asset di cui aggiornare la descrizione</param>
        /// <returns>string</returns>
        string UpdateDescription(AssetDTO body, string ID);

        /// <summary>
        /// Aggiorna la descrizione dell&#x27;asset
        /// </summary>
        /// <remarks>
        /// Aggiorna la descrizione di un asset di una sessione di gioco.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="ID">Identificativo dell&#x27;asset di cui aggiornare la descrizione</param>
        /// <returns>ApiResponse of string</returns>
        ApiResponse<string> UpdateDescriptionWithHttpInfo(AssetDTO body, string ID);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Aggiungi un giocatore
        /// </summary>
        /// <remarks>
        /// Aggiungi un giocatore di una sessione di gioco quando è in preparazione.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="ID">Identificativo dell&#x27;asset a cui aggiungere un giocatore</param>
        /// <returns>Task of string</returns>
        System.Threading.Tasks.Task<string> AddPlayerAsync(PlayerDTO body, string ID);

        /// <summary>
        /// Aggiungi un giocatore
        /// </summary>
        /// <remarks>
        /// Aggiungi un giocatore di una sessione di gioco quando è in preparazione.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="ID">Identificativo dell&#x27;asset a cui aggiungere un giocatore</param>
        /// <returns>Task of ApiResponse (string)</returns>
        System.Threading.Tasks.Task<ApiResponse<string>> AddPlayerAsyncWithHttpInfo(PlayerDTO body, string ID);
        /// <summary>
        /// Cambia stato di un asset
        /// </summary>
        /// <remarks>
        /// Cambia lo stato di una sessione di gioco.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="ID">Identificativo dell&#x27;asset di cui cambiare lo stato</param>
        /// <returns>Task of string</returns>
        System.Threading.Tasks.Task<string> ChangeStateAsync(AssetDTO body, string ID);

        /// <summary>
        /// Cambia stato di un asset
        /// </summary>
        /// <remarks>
        /// Cambia lo stato di una sessione di gioco.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="ID">Identificativo dell&#x27;asset di cui cambiare lo stato</param>
        /// <returns>Task of ApiResponse (string)</returns>
        System.Threading.Tasks.Task<ApiResponse<string>> ChangeStateAsyncWithHttpInfo(AssetDTO body, string ID);
        /// <summary>
        /// Crea un asset
        /// </summary>
        /// <remarks>
        /// Crea un nuovo asset che traccia una sessione di gioco.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>Task of string</returns>
        System.Threading.Tasks.Task<string> CreateAssetAsync(AssetDTO body);

        /// <summary>
        /// Crea un asset
        /// </summary>
        /// <remarks>
        /// Crea un nuovo asset che traccia una sessione di gioco.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>Task of ApiResponse (string)</returns>
        System.Threading.Tasks.Task<ApiResponse<string>> CreateAssetAsyncWithHttpInfo(AssetDTO body);
        /// <summary>
        /// Crea un evento
        /// </summary>
        /// <remarks>
        /// Aggiungi un evento per una sessione di gioco.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="ID">Identificativo dell&#x27;asset su cui registrare l&#x27;evento</param>
        /// <returns>Task of string</returns>
        System.Threading.Tasks.Task<string> CreateEventAsync(EventDTO body, string gameId, string eventId);

        /// <summary>
        /// Crea un evento
        /// </summary>
        /// <remarks>
        /// Aggiungi un evento per una sessione di gioco.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="ID">Identificativo dell&#x27;asset su cui registrare l&#x27;evento</param>
        /// <returns>Task of ApiResponse (string)</returns>
        System.Threading.Tasks.Task<ApiResponse<string>> CreateEventAsyncWithHttpInfo(EventDTO body, string gameId, string eventId);
        /// <summary>
        /// Dettagli utente
        /// </summary>
        /// <remarks>
        /// Recupera i dettagli dell&#x27;utente che interagisce con l&#x27;API.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of string</returns>
        System.Threading.Tasks.Task<string> GetClientIDAsync();

        /// <summary>
        /// Dettagli utente
        /// </summary>
        /// <remarks>
        /// Recupera i dettagli dell&#x27;utente che interagisce con l&#x27;API.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (string)</returns>
        System.Threading.Tasks.Task<ApiResponse<string>> GetClientIDAsyncWithHttpInfo();
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of string</returns>
        System.Threading.Tasks.Task<string> HelloAsync();

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (string)</returns>
        System.Threading.Tasks.Task<ApiResponse<string>> HelloAsyncWithHttpInfo();
        /// <summary>
        /// Leggi asset
        /// </summary>
        /// <remarks>
        /// Recupera tutti i dettagli di una sessione di gioco.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="ID">Identificativo dell&#x27;asset da leggere</param>
        /// <returns>Task of string</returns>
        System.Threading.Tasks.Task<string> ReadAssetAsync(string ID);

        /// <summary>
        /// Leggi asset
        /// </summary>
        /// <remarks>
        /// Recupera tutti i dettagli di una sessione di gioco.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="ID">Identificativo dell&#x27;asset da leggere</param>
        /// <returns>Task of ApiResponse (string)</returns>
        System.Threading.Tasks.Task<ApiResponse<string>> ReadAssetAsyncWithHttpInfo(string ID);
        /// <summary>
        /// Leggi evento
        /// </summary>
        /// <remarks>
        /// Recupera tutti i dettagli degli eventi inviati dall&#x27;utente.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="ID">Identificativo dell&#x27;asset da cui leggere gli eventi</param>
        /// <returns>Task of string</returns>
        System.Threading.Tasks.Task<string> ReadEventAsync(string ID);

        /// <summary>
        /// Leggi evento
        /// </summary>
        /// <remarks>
        /// Recupera tutti i dettagli degli eventi inviati dall&#x27;utente.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="ID">Identificativo dell&#x27;asset da cui leggere gli eventi</param>
        /// <returns>Task of ApiResponse (string)</returns>
        System.Threading.Tasks.Task<ApiResponse<string>> ReadEventAsyncWithHttpInfo(string ID);
        /// <summary>
        /// Rimuovi un giocatore
        /// </summary>
        /// <remarks>
        /// Rimuovi un giocatore da una sessione di gioco in corso.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="ID">Identificativo dell&#x27;asset da cui rimuovere un giocatore</param>
        /// <returns>Task of string</returns>
        System.Threading.Tasks.Task<string> RemovePlayerAsync(PlayerDTO body, string ID);

        /// <summary>
        /// Rimuovi un giocatore
        /// </summary>
        /// <remarks>
        /// Rimuovi un giocatore da una sessione di gioco in corso.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="ID">Identificativo dell&#x27;asset da cui rimuovere un giocatore</param>
        /// <returns>Task of ApiResponse (string)</returns>
        System.Threading.Tasks.Task<ApiResponse<string>> RemovePlayerAsyncWithHttpInfo(PlayerDTO body, string ID);
        /// <summary>
        /// Aggiorna la descrizione dell&#x27;asset
        /// </summary>
        /// <remarks>
        /// Aggiorna la descrizione di un asset di una sessione di gioco.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="ID">Identificativo dell&#x27;asset di cui aggiornare la descrizione</param>
        /// <returns>Task of string</returns>
        System.Threading.Tasks.Task<string> UpdateDescriptionAsync(AssetDTO body, string ID);

        /// <summary>
        /// Aggiorna la descrizione dell&#x27;asset
        /// </summary>
        /// <remarks>
        /// Aggiorna la descrizione di un asset di una sessione di gioco.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="ID">Identificativo dell&#x27;asset di cui aggiornare la descrizione</param>
        /// <returns>Task of ApiResponse (string)</returns>
        System.Threading.Tasks.Task<ApiResponse<string>> UpdateDescriptionAsyncWithHttpInfo(AssetDTO body, string ID);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class BlockchainReSTAPIApi : IBlockchainReSTAPIApi
    {
        private ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="BlockchainReSTAPIApi"/> class.
        /// </summary>
        /// <returns></returns>
        public BlockchainReSTAPIApi(string basePath)
        {
            Configuration = new Configuration { BasePath = basePath };

            ExceptionFactory = Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="BlockchainReSTAPIApi"/> class
        /// </summary>
        /// <returns></returns>
        public BlockchainReSTAPIApi()
        {
            Configuration = Configuration.Default;

            ExceptionFactory = Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="BlockchainReSTAPIApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public BlockchainReSTAPIApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                Configuration = Configuration.Default;
            else
                Configuration = configuration;

            ExceptionFactory = Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return Configuration.ApiClient.RestClient.Options.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(string basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<string, string> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Aggiungi un giocatore Aggiungi un giocatore di una sessione di gioco quando è in preparazione.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="ID">Identificativo dell&#x27;asset a cui aggiungere un giocatore</param>
        /// <returns>string</returns>
        public string AddPlayer(PlayerDTO body, string ID)
        {
            ApiResponse<string> localVarResponse = AddPlayerWithHttpInfo(body, ID);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Aggiungi un giocatore Aggiungi un giocatore di una sessione di gioco quando è in preparazione.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="ID">Identificativo dell&#x27;asset a cui aggiungere un giocatore</param>
        /// <returns>ApiResponse of string</returns>
        public ApiResponse<string> AddPlayerWithHttpInfo(PlayerDTO body, string ID)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling BlockchainReSTAPIApi->AddPlayer");
            // verify the required parameter 'ID' is set
            if (ID == null)
                throw new ApiException(400, "Missing required parameter 'ID' when calling BlockchainReSTAPIApi->AddPlayer");

            var localVarPath = "/api/addPlayer/{ID}";
            var localVarPathParams = new Dictionary<string, string>();
            var localVarQueryParams = new List<KeyValuePair<string, string>>();
            var localVarHeaderParams = new Dictionary<string, string>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<string, string>();
            var localVarFileParams = new Dictionary<string, FileParameter>();
            object localVarPostBody = null;

            // to determine the Content-Type header
            string[] localVarHttpContentTypes = new string[] {
                "application/json"
            };
            string localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            string[] localVarHttpHeaderAccepts = new string[] {
                "*/*"
            };
            string localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (ID != null) localVarPathParams.Add("ID", Configuration.ApiClient.ParameterToString(ID)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse)Configuration.ApiClient.CallApi(localVarPath,
                Method.Post, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int)localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("AddPlayer", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (string)Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

        /// <summary>
        /// Aggiungi un giocatore Aggiungi un giocatore di una sessione di gioco quando è in preparazione.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="ID">Identificativo dell&#x27;asset a cui aggiungere un giocatore</param>
        /// <returns>Task of string</returns>
        public async System.Threading.Tasks.Task<string> AddPlayerAsync(PlayerDTO body, string ID)
        {
            ApiResponse<string> localVarResponse = await AddPlayerAsyncWithHttpInfo(body, ID);
            return localVarResponse.Data;

        }

        /// <summary>
        /// Aggiungi un giocatore Aggiungi un giocatore di una sessione di gioco quando è in preparazione.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="ID">Identificativo dell&#x27;asset a cui aggiungere un giocatore</param>
        /// <returns>Task of ApiResponse (string)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<string>> AddPlayerAsyncWithHttpInfo(PlayerDTO body, string ID)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling BlockchainReSTAPIApi->AddPlayer");
            // verify the required parameter 'ID' is set
            if (ID == null)
                throw new ApiException(400, "Missing required parameter 'ID' when calling BlockchainReSTAPIApi->AddPlayer");

            var localVarPath = "/api/addPlayer/{ID}";
            var localVarPathParams = new Dictionary<string, string>();
            var localVarQueryParams = new List<KeyValuePair<string, string>>();
            var localVarHeaderParams = new Dictionary<string, string>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<string, string>();
            var localVarFileParams = new Dictionary<string, FileParameter>();
            object localVarPostBody = null;

            // to determine the Content-Type header
            string[] localVarHttpContentTypes = new string[] {
                "application/json"
            };
            string localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            string[] localVarHttpHeaderAccepts = new string[] {
                "*/*"
            };
            string localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (ID != null) localVarPathParams.Add("ID", Configuration.ApiClient.ParameterToString(ID)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse)await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.Post, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int)localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("AddPlayer", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (string)Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

        /// <summary>
        /// Cambia stato di un asset Cambia lo stato di una sessione di gioco.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="ID">Identificativo dell&#x27;asset di cui cambiare lo stato</param>
        /// <returns>string</returns>
        public string ChangeState(AssetDTO body, string ID)
        {
            ApiResponse<string> localVarResponse = ChangeStateWithHttpInfo(body, ID);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Cambia stato di un asset Cambia lo stato di una sessione di gioco.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="ID">Identificativo dell&#x27;asset di cui cambiare lo stato</param>
        /// <returns>ApiResponse of string</returns>
        public ApiResponse<string> ChangeStateWithHttpInfo(AssetDTO body, string ID)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling BlockchainReSTAPIApi->ChangeState");
            // verify the required parameter 'ID' is set
            if (ID == null)
                throw new ApiException(400, "Missing required parameter 'ID' when calling BlockchainReSTAPIApi->ChangeState");

            var localVarPath = "/api/changeState/{ID}";
            var localVarPathParams = new Dictionary<string, string>();
            var localVarQueryParams = new List<KeyValuePair<string, string>>();
            var localVarHeaderParams = new Dictionary<string, string>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<string, string>();
            var localVarFileParams = new Dictionary<string, FileParameter>();
            object localVarPostBody = null;

            // to determine the Content-Type header
            string[] localVarHttpContentTypes = new string[] {
                "application/json"
            };
            string localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            string[] localVarHttpHeaderAccepts = new string[] {
                "*/*"
            };
            string localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (ID != null) localVarPathParams.Add("ID", Configuration.ApiClient.ParameterToString(ID)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse)Configuration.ApiClient.CallApi(localVarPath,
                Method.Post, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int)localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ChangeState", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (string)Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

        /// <summary>
        /// Cambia stato di un asset Cambia lo stato di una sessione di gioco.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="ID">Identificativo dell&#x27;asset di cui cambiare lo stato</param>
        /// <returns>Task of string</returns>
        public async System.Threading.Tasks.Task<string> ChangeStateAsync(AssetDTO body, string ID)
        {
            ApiResponse<string> localVarResponse = await ChangeStateAsyncWithHttpInfo(body, ID);
            return localVarResponse.Data;

        }

        /// <summary>
        /// Cambia stato di un asset Cambia lo stato di una sessione di gioco.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="ID">Identificativo dell&#x27;asset di cui cambiare lo stato</param>
        /// <returns>Task of ApiResponse (string)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<string>> ChangeStateAsyncWithHttpInfo(AssetDTO body, string ID)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling BlockchainReSTAPIApi->ChangeState");
            // verify the required parameter 'ID' is set
            if (ID == null)
                throw new ApiException(400, "Missing required parameter 'ID' when calling BlockchainReSTAPIApi->ChangeState");

            var localVarPath = "/api/changeState/{ID}";
            var localVarPathParams = new Dictionary<string, string>();
            var localVarQueryParams = new List<KeyValuePair<string, string>>();
            var localVarHeaderParams = new Dictionary<string, string>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<string, string>();
            var localVarFileParams = new Dictionary<string, FileParameter>();
            object localVarPostBody = null;

            // to determine the Content-Type header
            string[] localVarHttpContentTypes = new string[] {
                "application/json"
            };
            string localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            string[] localVarHttpHeaderAccepts = new string[] {
                "*/*"
            };
            string localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (ID != null) localVarPathParams.Add("ID", Configuration.ApiClient.ParameterToString(ID)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse)await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.Post, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int)localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ChangeState", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (string)Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

        /// <summary>
        /// Crea un asset Crea un nuovo asset che traccia una sessione di gioco.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>string</returns>
        public string CreateAsset(AssetDTO body)
        {
            ApiResponse<string> localVarResponse = CreateAssetWithHttpInfo(body);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Crea un asset Crea un nuovo asset che traccia una sessione di gioco.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>ApiResponse of string</returns>
        public ApiResponse<string> CreateAssetWithHttpInfo(AssetDTO body)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling BlockchainReSTAPIApi->CreateAsset");

            var localVarPath = "/api/createAsset";
            var localVarPathParams = new Dictionary<string, string>();
            var localVarQueryParams = new List<KeyValuePair<string, string>>();
            var localVarHeaderParams = new Dictionary<string, string>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<string, string>();
            var localVarFileParams = new Dictionary<string, FileParameter>();
            object localVarPostBody = null;

            // to determine the Content-Type header
            string[] localVarHttpContentTypes = new string[] {
                "application/json"
            };
            string localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            string[] localVarHttpHeaderAccepts = new string[] {
                "*/*"
            };
            string localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse)Configuration.ApiClient.CallApi(localVarPath,
                Method.Post, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int)localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CreateAsset", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (string)Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

        /// <summary>
        /// Crea un asset Crea un nuovo asset che traccia una sessione di gioco.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>Task of string</returns>
        public async System.Threading.Tasks.Task<string> CreateAssetAsync(AssetDTO body)
        {
            ApiResponse<string> localVarResponse = await CreateAssetAsyncWithHttpInfo(body);
            return localVarResponse.Data;

        }

        /// <summary>
        /// Crea un asset Crea un nuovo asset che traccia una sessione di gioco.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>Task of ApiResponse (string)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<string>> CreateAssetAsyncWithHttpInfo(AssetDTO body)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling BlockchainReSTAPIApi->CreateAsset");

            var localVarPath = "/api/createAsset";
            var localVarPathParams = new Dictionary<string, string>();
            var localVarQueryParams = new List<KeyValuePair<string, string>>();
            var localVarHeaderParams = new Dictionary<string, string>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<string, string>();
            var localVarFileParams = new Dictionary<string, FileParameter>();
            object localVarPostBody = null;

            // to determine the Content-Type header
            string[] localVarHttpContentTypes = new string[] {
                "application/json"
            };
            string localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            string[] localVarHttpHeaderAccepts = new string[] {
                "*/*"
            };
            string localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse)await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.Post, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int)localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CreateAsset", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (string)Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

        /// <summary>
        /// Crea un evento Aggiungi un evento per una sessione di gioco.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="ID">Identificativo dell&#x27;asset su cui registrare l&#x27;evento</param>
        /// <returns>string</returns>
        public string CreateEvent(EventDTO body, string gameId, string eventId)
        {
            ApiResponse<string> localVarResponse = CreateEventWithHttpInfo(body, gameId, eventId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Crea un evento Aggiungi un evento per una sessione di gioco.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="ID">Identificativo dell&#x27;asset su cui registrare l&#x27;evento</param>
        /// <returns>ApiResponse of string</returns>
        public ApiResponse<string> CreateEventWithHttpInfo(EventDTO body, string gameID, string ID)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling BlockchainReSTAPIApi->CreateEvent");
            // verify the required parameter 'ID' is set
            if (gameID == null)
                throw new ApiException(400, "Missing required parameter 'gameId' when calling BlockchainReSTAPIApi->CreateEvent");
            if (ID == null)
                throw new ApiException(400, "Missing required parameter 'eventId' when calling BlockchainReSTAPIApi->CreateEvent");


            var localVarPath = "/api/createEvent/{gameID}/{ID}";
            var localVarPathParams = new Dictionary<string, string>();
            var localVarQueryParams = new List<KeyValuePair<string, string>>();
            var localVarHeaderParams = new Dictionary<string, string>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<string, string>();
            var localVarFileParams = new Dictionary<string, FileParameter>();
            object localVarPostBody = null;

            // to determine the Content-Type header
            string[] localVarHttpContentTypes = new string[] {
                "application/json"
            };
            string localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            string[] localVarHttpHeaderAccepts = new string[] {
                "*/*"
            };
            string localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (gameID != null) localVarPathParams.Add("gameID", Configuration.ApiClient.ParameterToString(gameID));
            if (ID != null) localVarPathParams.Add("ID", Configuration.ApiClient.ParameterToString(ID));

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse)Configuration.ApiClient.CallApi(localVarPath,
                Method.Post, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int)localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CreateEvent", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (string)Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

        /// <summary>
        /// Crea un evento Aggiungi un evento per una sessione di gioco.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="ID">Identificativo dell&#x27;asset su cui registrare l&#x27;evento</param>
        /// <returns>Task of string</returns>
        public async System.Threading.Tasks.Task<string> CreateEventAsync(EventDTO body, string gameId, string eventId)
        {
            ApiResponse<string> localVarResponse = await CreateEventAsyncWithHttpInfo(body, gameId, eventId);
            return localVarResponse.Data;

        }

        /// <summary>
        /// Crea un evento Aggiungi un evento per una sessione di gioco.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="ID">Identificativo dell&#x27;asset su cui registrare l&#x27;evento</param>
        /// <returns>Task of ApiResponse (string)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<string>> CreateEventAsyncWithHttpInfo(EventDTO body, string gameID, string ID)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling BlockchainReSTAPIApi->CreateEvent");
            if (gameID == null)
                throw new ApiException(400, "Missing required parameter 'gameID' when calling BlockchainReSTAPIApi->CreateEvent");
            if (ID == null)
                throw new ApiException(400, "Missing required parameter 'ID' when calling BlockchainReSTAPIApi->CreateEvent");


            var localVarPath = "/api/createEvent/{gameID}/{ID}";
            var localVarPathParams = new Dictionary<string, string>();
            var localVarQueryParams = new List<KeyValuePair<string, string>>();
            var localVarHeaderParams = new Dictionary<string, string>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<string, string>();
            var localVarFileParams = new Dictionary<string, FileParameter>();
            object localVarPostBody = null;

            // to determine the Content-Type header
            string[] localVarHttpContentTypes = new string[] {
                "application/json"
            };
            string localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            string[] localVarHttpHeaderAccepts = new string[] {
                "*/*"
            };
            string localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (gameID != null) localVarPathParams.Add("gameID", Configuration.ApiClient.ParameterToString(gameID)); // path parameter
            if (ID != null) localVarPathParams.Add("ID", Configuration.ApiClient.ParameterToString(ID)); // path parameter

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse)await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.Post, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int)localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CreateEvent", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (string)Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

        /// <summary>
        /// Dettagli utente Recupera i dettagli dell&#x27;utente che interagisce con l&#x27;API.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <returns>string</returns>
        public string GetClientID()
        {
            ApiResponse<string> localVarResponse = GetClientIDWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// Dettagli utente Recupera i dettagli dell&#x27;utente che interagisce con l&#x27;API.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of string</returns>
        public ApiResponse<string> GetClientIDWithHttpInfo()
        {

            var localVarPath = "/api/clientID";
            var localVarPathParams = new Dictionary<string, string>();
            var localVarQueryParams = new List<KeyValuePair<string, string>>();
            var localVarHeaderParams = new Dictionary<string, string>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<string, string>();
            var localVarFileParams = new Dictionary<string, FileParameter>();
            object localVarPostBody = null;

            // to determine the Content-Type header
            string[] localVarHttpContentTypes = new string[] {
            };
            string localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            string[] localVarHttpHeaderAccepts = new string[] {
                "*/*"
            };
            string localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);


            // make the HTTP request
            RestResponse localVarResponse = (RestResponse)Configuration.ApiClient.CallApi(localVarPath,
                Method.Get, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int)localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetClientID", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (string)Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

        /// <summary>
        /// Dettagli utente Recupera i dettagli dell&#x27;utente che interagisce con l&#x27;API.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of string</returns>
        public async System.Threading.Tasks.Task<string> GetClientIDAsync()
        {
            ApiResponse<string> localVarResponse = await GetClientIDAsyncWithHttpInfo();
            return localVarResponse.Data;

        }

        /// <summary>
        /// Dettagli utente Recupera i dettagli dell&#x27;utente che interagisce con l&#x27;API.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (string)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<string>> GetClientIDAsyncWithHttpInfo()
        {

            var localVarPath = "/api/clientID";
            var localVarPathParams = new Dictionary<string, string>();
            var localVarQueryParams = new List<KeyValuePair<string, string>>();
            var localVarHeaderParams = new Dictionary<string, string>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<string, string>();
            var localVarFileParams = new Dictionary<string, FileParameter>();
            object localVarPostBody = null;

            // to determine the Content-Type header
            string[] localVarHttpContentTypes = new string[] {
            };
            string localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            string[] localVarHttpHeaderAccepts = new string[] {
                "*/*"
            };
            string localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);


            // make the HTTP request
            RestResponse localVarResponse = (RestResponse)await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.Get, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int)localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetClientID", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (string)Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <returns>string</returns>
        public string Hello()
        {
            ApiResponse<string> localVarResponse = HelloWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of string</returns>
        public ApiResponse<string> HelloWithHttpInfo()
        {

            var localVarPath = "/api/hello";
            var localVarPathParams = new Dictionary<string, string>();
            var localVarQueryParams = new List<KeyValuePair<string, string>>();
            var localVarHeaderParams = new Dictionary<string, string>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<string, string>();
            var localVarFileParams = new Dictionary<string, FileParameter>();
            object localVarPostBody = null;

            // to determine the Content-Type header
            string[] localVarHttpContentTypes = new string[] {
            };
            string localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            string[] localVarHttpHeaderAccepts = new string[] {
                "*/*"
            };
            string localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);


            // make the HTTP request
            RestResponse localVarResponse = (RestResponse)Configuration.ApiClient.CallApi(localVarPath,
                Method.Get, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int)localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("Hello", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (string)Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of string</returns>
        public async System.Threading.Tasks.Task<string> HelloAsync()
        {
            ApiResponse<string> localVarResponse = await HelloAsyncWithHttpInfo();
            return localVarResponse.Data;

        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (string)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<string>> HelloAsyncWithHttpInfo()
        {

            var localVarPath = "/api/hello";
            var localVarPathParams = new Dictionary<string, string>();
            var localVarQueryParams = new List<KeyValuePair<string, string>>();
            var localVarHeaderParams = new Dictionary<string, string>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<string, string>();
            var localVarFileParams = new Dictionary<string, FileParameter>();
            object localVarPostBody = null;

            // to determine the Content-Type header
            string[] localVarHttpContentTypes = new string[] {
            };
            string localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            string[] localVarHttpHeaderAccepts = new string[] {
                "*/*"
            };
            string localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);


            // make the HTTP request
            RestResponse localVarResponse = (RestResponse)await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.Get, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int)localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("Hello", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (string)Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

        /// <summary>
        /// Leggi asset Recupera tutti i dettagli di una sessione di gioco.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="ID">Identificativo dell&#x27;asset da leggere</param>
        /// <returns>string</returns>
        public string ReadAsset(string ID)
        {
            ApiResponse<string> localVarResponse = ReadAssetWithHttpInfo(ID);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Leggi asset Recupera tutti i dettagli di una sessione di gioco.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="ID">Identificativo dell&#x27;asset da leggere</param>
        /// <returns>ApiResponse of string</returns>
        public ApiResponse<string> ReadAssetWithHttpInfo(string ID)
        {
            // verify the required parameter 'ID' is set
            if (ID == null)
                throw new ApiException(400, "Missing required parameter 'ID' when calling BlockchainReSTAPIApi->ReadAsset");

            var localVarPath = "/api/readAsset/{ID}";
            var localVarPathParams = new Dictionary<string, string>();
            var localVarQueryParams = new List<KeyValuePair<string, string>>();
            var localVarHeaderParams = new Dictionary<string, string>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<string, string>();
            var localVarFileParams = new Dictionary<string, FileParameter>();
            object localVarPostBody = null;

            // to determine the Content-Type header
            string[] localVarHttpContentTypes = new string[] {
            };
            string localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            string[] localVarHttpHeaderAccepts = new string[] {
                "*/*"
            };
            string localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (ID != null) localVarPathParams.Add("ID", Configuration.ApiClient.ParameterToString(ID)); // path parameter

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse)Configuration.ApiClient.CallApi(localVarPath,
                Method.Get, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int)localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ReadAsset", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (string)Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

        /// <summary>
        /// Leggi asset Recupera tutti i dettagli di una sessione di gioco.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="ID">Identificativo dell&#x27;asset da leggere</param>
        /// <returns>Task of string</returns>
        public async System.Threading.Tasks.Task<string> ReadAssetAsync(string ID)
        {
            ApiResponse<string> localVarResponse = await ReadAssetAsyncWithHttpInfo(ID);
            return localVarResponse.Data;

        }

        /// <summary>
        /// Leggi asset Recupera tutti i dettagli di una sessione di gioco.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="ID">Identificativo dell&#x27;asset da leggere</param>
        /// <returns>Task of ApiResponse (string)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<string>> ReadAssetAsyncWithHttpInfo(string ID)
        {
            // verify the required parameter 'ID' is set
            if (ID == null)
                throw new ApiException(400, "Missing required parameter 'ID' when calling BlockchainReSTAPIApi->ReadAsset");

            var localVarPath = "/api/readAsset/{ID}";
            var localVarPathParams = new Dictionary<string, string>();
            var localVarQueryParams = new List<KeyValuePair<string, string>>();
            var localVarHeaderParams = new Dictionary<string, string>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<string, string>();
            var localVarFileParams = new Dictionary<string, FileParameter>();
            object localVarPostBody = null;

            // to determine the Content-Type header
            string[] localVarHttpContentTypes = new string[] {
            };
            string localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            string[] localVarHttpHeaderAccepts = new string[] {
                "*/*"
            };
            string localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (ID != null) localVarPathParams.Add("ID", Configuration.ApiClient.ParameterToString(ID)); // path parameter

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse)await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.Get, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int)localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ReadAsset", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (string)Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

        /// <summary>
        /// Leggi evento Recupera tutti i dettagli degli eventi inviati dall&#x27;utente.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="ID">Identificativo dell&#x27;asset da cui leggere gli eventi</param>
        /// <returns>string</returns>
        public string ReadEvent(string ID)
        {
            ApiResponse<string> localVarResponse = ReadEventWithHttpInfo(ID);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Leggi evento Recupera tutti i dettagli degli eventi inviati dall&#x27;utente.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="ID">Identificativo dell&#x27;asset da cui leggere gli eventi</param>
        /// <returns>ApiResponse of string</returns>
        public ApiResponse<string> ReadEventWithHttpInfo(string ID)
        {
            // verify the required parameter 'ID' is set
            if (ID == null)
                throw new ApiException(400, "Missing required parameter 'ID' when calling BlockchainReSTAPIApi->ReadEvent");

            var localVarPath = "/api/readEvent/{ID}";
            var localVarPathParams = new Dictionary<string, string>();
            var localVarQueryParams = new List<KeyValuePair<string, string>>();
            var localVarHeaderParams = new Dictionary<string, string>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<string, string>();
            var localVarFileParams = new Dictionary<string, FileParameter>();
            object localVarPostBody = null;

            // to determine the Content-Type header
            string[] localVarHttpContentTypes = new string[] {
            };
            string localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            string[] localVarHttpHeaderAccepts = new string[] {
                "*/*"
            };
            string localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (ID != null) localVarPathParams.Add("ID", Configuration.ApiClient.ParameterToString(ID)); // path parameter

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse)Configuration.ApiClient.CallApi(localVarPath,
                Method.Get, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int)localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ReadEvent", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (string)Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

        /// <summary>
        /// Leggi evento Recupera tutti i dettagli degli eventi inviati dall&#x27;utente.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="ID">Identificativo dell&#x27;asset da cui leggere gli eventi</param>
        /// <returns>Task of string</returns>
        public async System.Threading.Tasks.Task<string> ReadEventAsync(string ID)
        {
            ApiResponse<string> localVarResponse = await ReadEventAsyncWithHttpInfo(ID);
            return localVarResponse.Data;

        }

        /// <summary>
        /// Leggi evento Recupera tutti i dettagli degli eventi inviati dall&#x27;utente.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="ID">Identificativo dell&#x27;asset da cui leggere gli eventi</param>
        /// <returns>Task of ApiResponse (string)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<string>> ReadEventAsyncWithHttpInfo(string ID)
        {
            // verify the required parameter 'ID' is set
            if (ID == null)
                throw new ApiException(400, "Missing required parameter 'ID' when calling BlockchainReSTAPIApi->ReadEvent");

            var localVarPath = "/api/readEvent/{ID}";
            var localVarPathParams = new Dictionary<string, string>();
            var localVarQueryParams = new List<KeyValuePair<string, string>>();
            var localVarHeaderParams = new Dictionary<string, string>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<string, string>();
            var localVarFileParams = new Dictionary<string, FileParameter>();
            object localVarPostBody = null;

            // to determine the Content-Type header
            string[] localVarHttpContentTypes = new string[] {
            };
            string localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            string[] localVarHttpHeaderAccepts = new string[] {
                "*/*"
            };
            string localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (ID != null) localVarPathParams.Add("ID", Configuration.ApiClient.ParameterToString(ID)); // path parameter

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse)await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.Get, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int)localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ReadEvent", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (string)Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

        /// <summary>
        /// Rimuovi un giocatore Rimuovi un giocatore da una sessione di gioco in corso.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="ID">Identificativo dell&#x27;asset da cui rimuovere un giocatore</param>
        /// <returns>string</returns>
        public string RemovePlayer(PlayerDTO body, string ID)
        {
            ApiResponse<string> localVarResponse = RemovePlayerWithHttpInfo(body, ID);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Rimuovi un giocatore Rimuovi un giocatore da una sessione di gioco in corso.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="ID">Identificativo dell&#x27;asset da cui rimuovere un giocatore</param>
        /// <returns>ApiResponse of string</returns>
        public ApiResponse<string> RemovePlayerWithHttpInfo(PlayerDTO body, string ID)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling BlockchainReSTAPIApi->RemovePlayer");
            // verify the required parameter 'ID' is set
            if (ID == null)
                throw new ApiException(400, "Missing required parameter 'ID' when calling BlockchainReSTAPIApi->RemovePlayer");

            var localVarPath = "/api/removePlayer/{ID}";
            var localVarPathParams = new Dictionary<string, string>();
            var localVarQueryParams = new List<KeyValuePair<string, string>>();
            var localVarHeaderParams = new Dictionary<string, string>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<string, string>();
            var localVarFileParams = new Dictionary<string, FileParameter>();
            object localVarPostBody = null;

            // to determine the Content-Type header
            string[] localVarHttpContentTypes = new string[] {
                "application/json"
            };
            string localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            string[] localVarHttpHeaderAccepts = new string[] {
                "*/*"
            };
            string localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (ID != null) localVarPathParams.Add("ID", Configuration.ApiClient.ParameterToString(ID)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse)Configuration.ApiClient.CallApi(localVarPath,
                Method.Post, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int)localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("RemovePlayer", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (string)Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

        /// <summary>
        /// Rimuovi un giocatore Rimuovi un giocatore da una sessione di gioco in corso.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="ID">Identificativo dell&#x27;asset da cui rimuovere un giocatore</param>
        /// <returns>Task of string</returns>
        public async System.Threading.Tasks.Task<string> RemovePlayerAsync(PlayerDTO body, string ID)
        {
            ApiResponse<string> localVarResponse = await RemovePlayerAsyncWithHttpInfo(body, ID);
            return localVarResponse.Data;

        }

        /// <summary>
        /// Rimuovi un giocatore Rimuovi un giocatore da una sessione di gioco in corso.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="ID">Identificativo dell&#x27;asset da cui rimuovere un giocatore</param>
        /// <returns>Task of ApiResponse (string)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<string>> RemovePlayerAsyncWithHttpInfo(PlayerDTO body, string ID)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling BlockchainReSTAPIApi->RemovePlayer");
            // verify the required parameter 'ID' is set
            if (ID == null)
                throw new ApiException(400, "Missing required parameter 'ID' when calling BlockchainReSTAPIApi->RemovePlayer");

            var localVarPath = "/api/removePlayer/{ID}";
            var localVarPathParams = new Dictionary<string, string>();
            var localVarQueryParams = new List<KeyValuePair<string, string>>();
            var localVarHeaderParams = new Dictionary<string, string>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<string, string>();
            var localVarFileParams = new Dictionary<string, FileParameter>();
            object localVarPostBody = null;

            // to determine the Content-Type header
            string[] localVarHttpContentTypes = new string[] {
                "application/json"
            };
            string localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            string[] localVarHttpHeaderAccepts = new string[] {
                "*/*"
            };
            string localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (ID != null) localVarPathParams.Add("ID", Configuration.ApiClient.ParameterToString(ID)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse)await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.Post, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int)localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("RemovePlayer", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (string)Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

        /// <summary>
        /// Aggiorna la descrizione dell&#x27;asset Aggiorna la descrizione di un asset di una sessione di gioco.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="ID">Identificativo dell&#x27;asset di cui aggiornare la descrizione</param>
        /// <returns>string</returns>
        public string UpdateDescription(AssetDTO body, string ID)
        {
            ApiResponse<string> localVarResponse = UpdateDescriptionWithHttpInfo(body, ID);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Aggiorna la descrizione dell&#x27;asset Aggiorna la descrizione di un asset di una sessione di gioco.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="ID">Identificativo dell&#x27;asset di cui aggiornare la descrizione</param>
        /// <returns>ApiResponse of string</returns>
        public ApiResponse<string> UpdateDescriptionWithHttpInfo(AssetDTO body, string ID)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling BlockchainReSTAPIApi->UpdateDescription");
            // verify the required parameter 'ID' is set
            if (ID == null)
                throw new ApiException(400, "Missing required parameter 'ID' when calling BlockchainReSTAPIApi->UpdateDescription");

            var localVarPath = "/api/updateDescription/{ID}";
            var localVarPathParams = new Dictionary<string, string>();
            var localVarQueryParams = new List<KeyValuePair<string, string>>();
            var localVarHeaderParams = new Dictionary<string, string>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<string, string>();
            var localVarFileParams = new Dictionary<string, FileParameter>();
            object localVarPostBody = null;

            // to determine the Content-Type header
            string[] localVarHttpContentTypes = new string[] {
                "application/json"
            };
            string localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            string[] localVarHttpHeaderAccepts = new string[] {
                "*/*"
            };
            string localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (ID != null) localVarPathParams.Add("ID", Configuration.ApiClient.ParameterToString(ID)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse)Configuration.ApiClient.CallApi(localVarPath,
                Method.Post, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int)localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UpdateDescription", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (string)Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

        /// <summary>
        /// Aggiorna la descrizione dell&#x27;asset Aggiorna la descrizione di un asset di una sessione di gioco.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="ID">Identificativo dell&#x27;asset di cui aggiornare la descrizione</param>
        /// <returns>Task of string</returns>
        public async System.Threading.Tasks.Task<string> UpdateDescriptionAsync(AssetDTO body, string ID)
        {
            ApiResponse<string> localVarResponse = await UpdateDescriptionAsyncWithHttpInfo(body, ID);
            return localVarResponse.Data;

        }

        /// <summary>
        /// Aggiorna la descrizione dell&#x27;asset Aggiorna la descrizione di un asset di una sessione di gioco.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="ID">Identificativo dell&#x27;asset di cui aggiornare la descrizione</param>
        /// <returns>Task of ApiResponse (string)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<string>> UpdateDescriptionAsyncWithHttpInfo(AssetDTO body, string ID)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling BlockchainReSTAPIApi->UpdateDescription");
            // verify the required parameter 'ID' is set
            if (ID == null)
                throw new ApiException(400, "Missing required parameter 'ID' when calling BlockchainReSTAPIApi->UpdateDescription");

            var localVarPath = "/api/updateDescription/{ID}";
            var localVarPathParams = new Dictionary<string, string>();
            var localVarQueryParams = new List<KeyValuePair<string, string>>();
            var localVarHeaderParams = new Dictionary<string, string>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<string, string>();
            var localVarFileParams = new Dictionary<string, FileParameter>();
            object localVarPostBody = null;

            // to determine the Content-Type header
            string[] localVarHttpContentTypes = new string[] {
                "application/json"
            };
            string localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            string[] localVarHttpHeaderAccepts = new string[] {
                "*/*"
            };
            string localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (ID != null) localVarPathParams.Add("ID", Configuration.ApiClient.ParameterToString(ID)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse)await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.Post, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int)localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UpdateDescription", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (string)Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

    }
}
