/* 
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing BlockchainReSTAPIApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class BlockchainReSTAPIApiTests
    {
        private BlockchainReSTAPIApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new BlockchainReSTAPIApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BlockchainReSTAPIApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' BlockchainReSTAPIApi
            //Assert.IsInstanceOfType(typeof(BlockchainReSTAPIApi), instance, "instance is a BlockchainReSTAPIApi");
        }

        /// <summary>
        /// Test AddPlayer
        /// </summary>
        [Test]
        public void AddPlayerTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //PlayerDTO body = null;
            //string ID = null;
            //var response = instance.AddPlayer(body, ID);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        /// <summary>
        /// Test ChangeState
        /// </summary>
        [Test]
        public void ChangeStateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //AssetDTO body = null;
            //string ID = null;
            //var response = instance.ChangeState(body, ID);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        /// <summary>
        /// Test CreateAsset
        /// </summary>
        [Test]
        public void CreateAssetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //AssetDTO body = null;
            //var response = instance.CreateAsset(body);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        /// <summary>
        /// Test CreateEvent
        /// </summary>
        [Test]
        public void CreateEventTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //EventDTO body = null;
            //string ID = null;
            //var response = instance.CreateEvent(body, ID);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        /// <summary>
        /// Test GetClientID
        /// </summary>
        [Test]
        public void GetClientIDTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetClientID();
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        /// <summary>
        /// Test Hello
        /// </summary>
        [Test]
        public void HelloTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.Hello();
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        /// <summary>
        /// Test ReadAsset
        /// </summary>
        [Test]
        public void ReadAssetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string ID = null;
            //var response = instance.ReadAsset(ID);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        /// <summary>
        /// Test ReadEvent
        /// </summary>
        [Test]
        public void ReadEventTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string ID = null;
            //var response = instance.ReadEvent(ID);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        /// <summary>
        /// Test RemovePlayer
        /// </summary>
        [Test]
        public void RemovePlayerTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //PlayerDTO body = null;
            //string ID = null;
            //var response = instance.RemovePlayer(body, ID);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        /// <summary>
        /// Test UpdateDescription
        /// </summary>
        [Test]
        public void UpdateDescriptionTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //AssetDTO body = null;
            //string ID = null;
            //var response = instance.UpdateDescription(body, ID);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
    }

}
