/* 
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// Asset per tracciare una sessione di gioco
    /// </summary>
    [DataContract]
        public partial class AssetDTO :  IEquatable<AssetDTO>, IValidatableObject
    {
        /// <summary>
        /// stato
        /// </summary>
        /// <value>stato</value>
        [JsonConverter(typeof(StringEnumConverter))]
                public enum StatoEnum
        {
            /// <summary>
            /// Enum Incorso for value: in corso
            /// </summary>
            [EnumMember(Value = "in corso")]
            Incorso = 1,
            /// <summary>
            /// Enum Chiuso for value: chiuso
            /// </summary>
            [EnumMember(Value = "chiusa")]
            Chiuso = 2        }
        /// <summary>
        /// stato
        /// </summary>
        /// <value>stato</value>
        [DataMember(Name="stato", EmitDefaultValue=false)]
        public StatoEnum? Stato { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="AssetDTO" /> class.
        /// </summary>
        /// <param name="descrizione">descrizione della sessione di gioco.</param>
        /// <param name="stato">stato.</param>
        /// <param name="id">id.</param>
        public AssetDTO(string descrizione = default(string), StatoEnum? stato = default(StatoEnum?), string id = default(string))
        {
            this.Descrizione = descrizione;
            this.Stato = stato;
            this.Id = id;
        }
        
        /// <summary>
        /// descrizione della sessione di gioco
        /// </summary>
        /// <value>descrizione della sessione di gioco</value>
        [DataMember(Name="descrizione", EmitDefaultValue=false)]
        public string Descrizione { get; set; }


        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public string Id { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AssetDTO {\n");
            sb.Append("  Descrizione: ").Append(Descrizione).Append("\n");
            sb.Append("  Stato: ").Append(Stato).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AssetDTO);
        }

        /// <summary>
        /// Returns true if AssetDTO instances are equal
        /// </summary>
        /// <param name="input">Instance of AssetDTO to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AssetDTO input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Descrizione == input.Descrizione ||
                    (this.Descrizione != null &&
                    this.Descrizione.Equals(input.Descrizione))
                ) && 
                (
                    this.Stato == input.Stato ||
                    (this.Stato != null &&
                    this.Stato.Equals(input.Stato))
                ) && 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Descrizione != null)
                    hashCode = hashCode * 59 + this.Descrizione.GetHashCode();
                if (this.Stato != null)
                    hashCode = hashCode * 59 + this.Stato.GetHashCode();
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
