/* 
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AssetDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AssetDTOTests
    {
        // TODO uncomment below to declare an instance variable for AssetDTO
        //private AssetDTO instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AssetDTO
            //instance = new AssetDTO();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AssetDTO
        /// </summary>
        [Test]
        public void AssetDTOInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AssetDTO
            //Assert.IsInstanceOfType<AssetDTO> (instance, "variable 'instance' is a AssetDTO");
        }


        /// <summary>
        /// Test the property 'Descrizione'
        /// </summary>
        [Test]
        public void DescrizioneTest()
        {
            // TODO unit test for the property 'Descrizione'
        }
        /// <summary>
        /// Test the property 'Stato'
        /// </summary>
        [Test]
        public void StatoTest()
        {
            // TODO unit test for the property 'Stato'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

    }

}
