/* 
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing PlayerDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PlayerDTOTests
    {
        // TODO uncomment below to declare an instance variable for PlayerDTO
        //private PlayerDTO instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PlayerDTO
            //instance = new PlayerDTO();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PlayerDTO
        /// </summary>
        [Test]
        public void PlayerDTOInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PlayerDTO
            //Assert.IsInstanceOfType<PlayerDTO> (instance, "variable 'instance' is a PlayerDTO");
        }


        /// <summary>
        /// Test the property 'PlayerId'
        /// </summary>
        [Test]
        public void PlayerIdTest()
        {
            // TODO unit test for the property 'PlayerId'
        }
        /// <summary>
        /// Test the property 'Descrizione'
        /// </summary>
        [Test]
        public void DescrizioneTest()
        {
            // TODO unit test for the property 'Descrizione'
        }

    }

}
